= Examples
:render_as: Level4
:v291_section: 10.7+

== EXAMPLE TRANSACTIONS

=== Request and Receive New Appointment - Event S01

The patient has been seen by his primary care physician, Dr. Patricia Primary, and requires treatment by a cardiologist. The PCP requests a new appointment with Dr. Pump at the North Office. The patient has requested that the appointment be scheduled for a time between January 2nd and January 10th, 2007, and between 8:00 AM and 5:00 PM. Dr. Pump's office responds to the request with an appointment at the North Office at 9:30 AM on January 6, 2007.

MSH|^~\&|PRIMARY|EWHIN|SPOCARD|EWHIN|200701010800||SRM^S01^SRM_S01|090849PRIMARY|P|2.8|||AL|AL|||<cr>

ARQ|19940047^SCH001|||||047^Referral||NORMAL|||199401020800^199401101700||||0045^Contact^Carrie^S^^^||||3372^Person^Entered||||<cr>

PID||4875439|484848||Everyman^Adam^A^^| |19401121|M|Alias||2222 Home Street^Jay^WA^99021||555-2003|||M|||444-33-3333|||||||||||<cr>

DG1|001|I9|786.5|CHEST PAINS|200701010730|W|||||||||||||<cr>

DG1|002|I9|412|OLD MYOCARDIAL INFARCTION|200701010730|W|||||||||||||<cr>

RGS|001|<cr>

AIP|001||032^Pump^Patrick|002^CARDIOLOGIST|||||||NO|<cr>

AIL|001|^NORTH OFFICE|002^CLINIC|||||||YES|<cr>

MSH|^~\&|PRIMARY|EWHIN|JONES|EWHIN|200701010802||ACK|021244SPOCARD|P|2.8||||||<cr>

MSA|CA|090849JONES||||<cr>

MSH|^~\&|PRIMARY|EWHIN|JONES|EWHIN|200701010810||SRR^S01^SRR_S01|0934849SPOCARD|P|2.8|||||||<cr>

MSA|AA|090849EVERYMAN||||<cr>

SCH|2007047^SCH001|2007567^SCH100|||||047^Referral|NORMAL||||0045^Contact^Carrie^C^^^|555-2010|||087^By^Entered^^^^|555-2011||||BOOKED<cr>

TQ1||||||30^M|200701060930|200701061000||||||<cr>

PID||4875439|484848||Everyman^Adam^A^^||19401121|M|Alias||2222 Home Street^Jay^WA^99021||555-2003|||M|||444-22-3333|||||||||||<cr>

RGS|001|<cr>

AIP|001|032^Pump^Patrick|002^CARDIOLOGIST|||||||NO|BOOKED<cr>

AIL|001|103^NORTH OFFICE|002^CLINIC|||||||NO|BOOKED<cr>

MSH|^~\&|PRIMARY|EWHIN|SPOCARD|EWHIN|200701010812||ACK|434532JONES|P|2.8||||||<cr>

MSA|CA|0934849SPOCARD||||<cr>

=== Unsolicited Notification of Rescheduled Appointment - Event S13

The patient has asked Dr. Pump to reschedule his January 6th appointment. Dr. Primary’s scheduling application (the filler application) sends the PCP, Dr. Primary, a notification that the original appointment has been rescheduled, followed by a notification of the new appointment on January 9th at 1:00 PM.

MSH|^~\&|PRIMARY|EWHIN|JONES|EWHIN|200701040800||SIU^S13^SIU_S12|021244SPOCARD|P|2.8|||AL|ER||<cr>

SCH|2007047^SCH001|2007567^SCH100|||||047^Referral|NORMAL||||0045^Contact^Carrie^C^^^|555-2010|||087^By^Entered^^^^|555-2011||||BOOKED<cr>

TQ1||||||30^M|200701091300|200701091330||||||<cr>

NTE||The patient is going to be on vacation so cannot make previous appointment scheduled on January 6.<cr>

PID||4875439|484848||Everyman^Adam^A^^||19401121|M|Alias||2222 Home Street^Jay^WA^99021||555-2003|||M|||444-22-3333|||||||||||<cr>

RGS|001|<cr>

AIP|001|032^Pump^Patrick|002^CARDIOLOGIST|||||||NO|BOOKED<cr>

AIL|001|103^NORTH OFFICE|002^CLINIC|||||||NO|BOOKED<cr>

MSH|^~\&|PRIMARY|EWHIN|SPOCARD|EWHIN|200701010802||ACK|035324PRIMARY|P|2.8||||||<cr>

MSA|CA|021244SPOCARD||||<cr>

=== Request and Receive New Appointment with Repeating Interval - Event S01

The patient has been seen by his specialist, Dr. Specialize, and requires treatment by a physical therapist, Seth Stretcher. Dr. Specialize's office requests a one-hour appointment each day for the next five days. Mr. Stretcher's office responds to the request with an appointment at 9:30 AM on June 20th through June 24th, 2007.

MSH|^~\&|SPECIALIZE|EWHIN|STRETCHER|EWHIN|200706190800||SRM^S01^SRM_S01|03432SPECIALIZE|P|2.8|||AL|AL||<cr>

ARQ|20070347^SCH001|||||047^Referral||NORMAL|060|min|200706200930||Q1D|D5|00335^Specialize^Sara^S^^^MD||||A3423^Person^Entered||||<cr>

PID||4875439|484848||Everyman^Adam^A^^| |19401121|M|Alias||2222 Home Street^Jay^WA^99021||555-2003|||M||444-33-3333||||||||||<cr>

DG1|001|I9|833.00|Closed dislocation wrist|200706190700|||||||||||||<cr>

RGS|001|<cr>

AIP|001|064^STRETCHER^SETH|097^PHYSICAL THERAPIST|||||||NO|<cr>

AIL|001|103^NORTH OFFICE|002^CLINIC|||||||NO|<cr>

MSH|^~\&|SPECIALIZE|EWHIN|SMITH|EWHIN|200706190802||ACK|546644STRETCHER|P|2.8||||||<cr>

MSA|CA|03432SPECIALIZE||||<cr>

MSH|^~\&|STRETCHER|EWHIN|SPECIALIZE|EWHIN|200706190810||SRR^S01^SRR_S01|0654544JONES|P|2.8||||||<cr>

MSA|AA|03432SSPECIALIZE||||<cr>

SCH|2007037^SCH001|2007297^SCH100|||||047^Referral|NORMAL|| ||0335^Contact^Carrie^C^^^||||064^By^Entered|||||BOOKED<cr>

TQ1|||Q1D||5^D|60^M|200706200930|200706240930||||||<cr>

PID||4875439|484848||Everyman^Adam^A^^||19401121|M|Alias||2222 Home Street^Jay^WA^99021||555-2003|||M|||444-33-3333|||||||||||<cr>

RGS|001|<cr>

AIP|001|064^STRETCHER^SETH|097^PHYSICAL THERAPIST|||||||NO|BOOKED<cr>

AIL|001|103^NORTH OFFICE|002^CLINIC|||||||NO|BOOKED<cr>

MSH|^~\&|SPECIALIZE|EWHIN|STRETCHER|EWHIN|200706190800||ACK|045742SPECIALIZE|P|2.8||||||<cr>

MSA|CA|0654544JONES||||<cr>

