= Dev Notes

== How to maintain structure of site
A structure / map map be created that is a reference and this reference can be used to validate the links that are in individual pages.

- Links will need to be maintained manually in files in order for them to occur in the right places.
- Not all links will be maintained in the "map".  Obviously we can't do that given that, e.g., all references to data types, fields, segments, etc. will be links.

== How to manage edits by user?
- We should use branches
* Should branches be centered on users or issues?  Probably issues.
* Branches should have names that either A) indication the Jira issue (preferred?) of B) describe the issue
* No commits/push to main branch.  Edits must be made in a branch and then a PR submitted.


== There is no autosave for VSCode online
This is a bummer...





== Requirements (ranked 1-10 importance):
- 6 - Autosave
- 9 - Store as files
- 6 - IG Publisher integration?
- ? - Jira Integration
- 6 - Rendered as you edit (WYSI(kinda)WYG)
- 7 - diff between versions / edits



== GitLab vs GitHub
- GitLab WebIDE easier to use
* Launch from labeled button instead of pressing '.' or changing url
* preview pane for AsciiDoc not yet available.  Should be soon(??)
- GitLab diff easier to use
* GitLab menu item vs GitHub change of url
- GitLab already integrated with Jira

