= Dev Notes

== How to maintain structure of site
A structure / map map be created that is a reference and this reference can be used to validate the links that are in individual pages.

- Links will need to be maintained manually in files in order for them to occur in the right places.
- Not all links will be maintained in the "map".  Obviously we can't do that given that, e.g., all references to data types, fields, segments, etc. will be links.

== How to manage edits by user?
- We should use branches
* Should branches be centered on users or issues?  Probably issues.
* Branches should have names that either A) indication the Jira issue (preferred?) of B) describe the issue
* No commits/push to main branch.  Edits must be made in a branch and then a PR submitted.


== Requirements (ranked 1-10 importance):
- 6 - Autosave
- 9 - Store as files
- 6 - IG Publisher integration?
- ? - Jira Integration
- 6 - Rendered as you edit (WYSI(kinda)WYG)
- 7 - diff between versions / edits
- CI builds
- branch builds
- A place to host builds (even if they are done manually).  This should be at HL7.
- Documentation
* For tooling maintainers
* For tooling users


== GitLab vs GitHub
=== AutoSave
* GitHub has autosave feature (as long as you enable it)
* GitLab doesn't have autosave
* Autosave is not going to be bulletproof if you are editing the same file in multiple tabs/windows/computers.  This isn't Google Docs.

=== WebIDE easier to use
* GitLab launches from labeled button 
* GitHub must press '.' or change url

=== Preview pane (side by side)
* GitHub has it
* GitLab not yet available.  Should be soon(??)

=== Diff
* GitLab easier to use - menu item
* GitHub must change url with "/compare"

=== Jira integration
* GitLab already working within HL7
* GitHub could work
