= Message - S06 Request Appointment Deletion
:render_as: Message Page
:v291_section: 10.3;10.3.6

Placer request and filler response transactions are the messages and trigger events used between placer applications and filler applications. The placer application initiates transactions using the *SRM* message, requesting that the filler application modify its schedule(s) with the given trigger event and information. The filler application responds to these requests, using the *SRR* message, to either grant or deny the requests from the placer application.

When initiating a request, the placer application will generate and send an *SRM* message containing all of the information necessary to communicate the desired action to the filler application. All required segments and fields (both explicitly required and conditionally required) should be provided to the filler application, as defined in this chapter. When the filler application receives the transaction, it acknowledges it with the appropriate accept acknowledgment using an *ACK* message (assuming that the enhanced acknowledgment mode is in use). After processing the request at the application level, the filler acknowledges the transaction with the appropriate application acknowledgment in an *SRR* message (again assuming that an application acknowledgment was requested under the enhanced acknowledgment mode, or that the original acknowledgment mode is in use). Applying the explanations of the various application acknowledgment codes in the context of this chapter, an application accept from the filler means that the request was processed and accepted by the filler. An application error from the filler means that the request was processed and denied. An application reject from the filler means that the request was not, and could not, be processed due to one or more reasons unrelated to its content (for example: it fails the basic application protocol validation, the filler system is down, or there was an internal error). When appropriate, an *SRR* message with an application accept acknowledgment will contain further information on the request that was processed.

There are no unsolicited messages initiated from a filler application defined in this set of trigger events. Those messages and trigger events are defined below, in Section _10.4_, "_FILLER APPLICATION MESSAGES AND TRIGGER EVENTS UNSOLICITED_."

All of the trigger events associated with placer request and filler response transactions use a common message definition that follows:

SRM^S01-S11^SRM_S01: Schedule Request Message

[width="98%",cols="2%,31%,47%,9%,11%",options="header",]

|===

|Segments | |Description |Status |Chapter

|MSH | |Message Header | |2

|ARQ | |Appointment Request Information | |10

|[ APR ] | |Appointment Preferences | |10

|[\{NTE}] | |Notes and Comments for the ARQ | |2

|[\{ | |--- PATIENT begin | |

|PID | |Patient Identification | |3

|[ \{ GSP } ] |Person Gender and Sex | |3 |

|[ \{ GSR } ] |Recorded Gender and Sex | |3 |

|[ \{ GSC } ] |Sex Parameter for Clinical Use | |3 |

|[ \{ PRT } ] | |Participation | |4

|[ PV1 ] | |Patient Visit | |3

|[ PV2 ] | |Patient Visit - Additional Info | |3

|[ \{ PRT } ] | |Participation | |4

|[\{ | | | |

|OBX | |Observation/Result | |7

|[\{PRT}] | |Participation Information | |7

|}] | | | |

|[\{DG1}] | |Diagnosis | |6

|}] | |--- PATIENT end | |

|\{ | |--- RESOURCES begin | |

|RGS | |Resource Group Segment | |10

|[\{ | |--- SERVICE begin | |

|AIS | |Appointment Information - Service | |10

|[ APR ] | |Appointment Preferences | |10

|[\{NTE}] | |Notes and Comments for the AIS | |2

|}] | |--- SERVICE end | |

|[\{ | |--- GENERAL_RESOURCE begin | |

|AIG | |Appointment Information - General Resource | |10

|[ APR ] | |Appointment Preferences | |10

|[\{NTE}] | |Notes and Comments for the AIG | |2

|}] | |--- GENERAL_RESOURCE end | |

|[\{ | |--- LOCATION_RESOURCE begin | |

|AIL | |Appointment Information - Location Resource | |10

|[ APR ] | |Appointment Preferences | |10

|[\{NTE}] | |Notes and Comments for the AIL | |2

|}] | |--- LOCATION_RESOURCE end | |

|[\{ | |--- PERSONNEL_RESOURCE begin | |

|AIP | |Appointment Information - Personnel Resource | |10

|[ APR ] | |Appointment Preferences | |10

|[\{NTE}] | |Notes and Comments for the AIP | |2

|}] | |--- PERSONNEL_RESOURCE end | |

|} | |--- RESOURCES end | |

|===

[width="100%",cols="18%,24%,5%,16%,19%,18%",options="header",]

|===

|Acknowledgment Choreography | | | | |

|SRM^S01-S11^SRM_S01 | | | | |

|Field name |Field Value: Original mode |Field value: Enhanced mode | | |

|MSH-15 |Blank |NE |AL, SU, ER |NE |AL, SU, ER

|MSH-16 |Blank |NE |NE |AL, SU, ER |AL, SU, ER

|Immediate Ack |- |- |ACK^S01-S11^ACK |- |ACK^S01-S11^ACK

|Application Ack |SRR^S01-S11^SRR_S01 |- |- |SRR^S01-S11^SRR_S01 |SRR^S01-S11^SRR_S01

|===

SRR^S01-S11^SRR_S01: Scheduled Request Response

[width="97%",cols="4%,30%,1%,46%,2%,7%,2%,8%",options="header",]

|===

|Segments | |Description | |Status | |Chapter |

|MSH | |Message Header | | | |2 |

|MSA | |Message Acknowledgment | | | |2 |

|[ \{ ERR } ] | |Error Information | | | |2 |

|[ | |--- SCHEDULE begin | | | | |

|link:#SCH[SCH] | |Schedule Activity Information | | | |10 |

|[ \{ TQ1 } ] | |Timing/Quantity | | | |4 |

|[ \{ NTE } ] | |Notes and Comments for the SCH | | | |2 |

|[\{ | |--- PATIENT begin | | | | |

|PID | |Patient Identification | | | |3 |

|[ \{ GSP } ] | |Person Gender and Sex | | | |3 |

|[ \{ GSR } ] | |Recorded Gender and Sex | | | |3 |

|[ \{ GSC } ] | |Sex Parameter for Clinical Use | | | |3 |

|[ \{ PRT } ] | |Participation | | | |4 |

|[ PV1 ] | |Patient Visit | | | |3 |

|[ PV2 ] | |Patient Visit - Additional Info | | | |3 |

|[ \{ PRT } ] | |Participation | | | |4 |

|[ \{ DG1 } ] | |Diagnosis | | | |6 |

|}] | |--- PATIENT end | | | | |

|\{ | |--- RESOURCES begin | | | | |

|link:#RGS[RGS] | |Resource Group Segment | | | |10 |

|[ \{ | |--- SERVICE begin | | | | |

|link:#AIS[AIS] | |Appointment Information - Service | | | |10 |

|[ \{ NTE } ] | |Notes and Comments for the RGS | | | |2 |

|} ] | |--- SERVICE end | | | | |

|[ \{ | |--- GENERAL_RESOURCE begin | | | | |

|link:#AIG[AIG] | |Appointment Information - General Resource | | | |10 |

|[ \{ NTE } ] | |Notes and Comments for the AIG | | | |2 |

|} ] | |--- GENERAL_RESOURCE end | | | | |

|[ \{ | |--- LOCATION_RESOURCE begin | | | | |

|link:#AIL[AIL] | |Appointment Information - Location Resource | | | |10 |

|[ \{ NTE } ] | |Notes and Comments for the AIL | | | |2 |

|} ] | |--- LOCATION_RESOURCE end | | | | |

|[ \{ | |--- PERSONNEL_RESOURCE begin | | | | |

|link:#AIP[AIP] | |Appointment Information - Personnel Resource | | | |10 |

|[ \{ NTE } ] | |Notes and Comments for the AIP | | | |2 |

|} ] | |--- PERSONNEL_RESOURCE end | | | | |

|} | |--- RESOURCES end | | | | |

|] | |--- SCHEDULE end | | | | |

|===

Note that in the abstract message definitions for both the SRM and SRR, the patient information segments (segments PID through DG1) are both optional as a group, and repeating as a group. The optionality allows for transactions that relate to a patient, and for those that do not. The ability to repeat the patient information allows for those transactions in which one activity must be scheduled for multiple patients (e.g., for family or group therapy).

In contrast, a transaction may specify no more than (and no less than) one activity. Note that neither the ARQ segment (in the SRM message) nor the SCH segment (in the SRR message) are allowed to repeat, and that they are required. Neither the optionality nor the ability to repeat patient information allows a transaction to specify more than one activity.

The trigger events that use this message definition are listed below.

[width="100%",cols="19%,32%,15%,34%",options="header",]

|===

|Acknowledgment Choreography | | |

|SRR^S01-S11^SRR_S01 | | |

|Field name |Field Value: Original mode |Field value: Enhanced mode |

|MSH-15 |Blank |NE |AL, SU, ER

|MSH-16 |Blank |NE |NE

|Immediate Ack |- |- |ACK^S01-S11^ACK

|Application Ack |- |- |-

|===

A request appointment deletion is sent by the placer application to the filler application to request that an appointment that had been entered in error be removed from the system. A delete trigger event should only be used when an appointment has been erroneously requested, and must be removed from the schedule so that it does not affect any statistical processing. A delete trigger event differs from a cancel trigger event in that a delete acts to remove an error, whereas a cancel acts to prevent a valid request from occurring. This trigger event should not be used for any appointment that has already begun, or has already been completed. Likewise, it should not be used on any parent appointment if any child appointments have either begun or been completed. If it is successful, an application acknowledgment is returned, optionally containing an SCH segment and related detail segments describing the deleted appointment.

The delete trigger event should be implemented with careful forethought, as it typically has different effects and repercussions in various applications. In some applications, a delete event cannot be undone. This means that if a delete transaction was sent erroneously, recovery will be difficult or impossible. In other applications, a delete transaction will not result in the physical deletion of the record(s), but will set a status or a flag. In these cases, the filler and/or placer appointment identifiers (the numbers or codes that uniquely identify the scheduled appointment or request to the placer and filler applications) probably cannot be reused. Since these applications maintain a record of deleted appointments, the reuse of an identifier will likely cause a conflict in the applications' processing of transactions.

[message-tabs, ["SRM^S06^SRM_S01", "SRM Interaction", "ACK^S06^ACK", "ACK Interaction", "SRR^S06^SRR_S01", "SRR Interaction"]]

