= Examples
:render_as: Level4
:v291_section: 11.9+ (minus 11.9.6)

== EXAMPLES

=== RQI Message Using an I01 Event with an Immediate Response

When a patient arrives for an appointment, the office staff will frequently need to verify the patient's insurance information. In the following RQI message example, Dr. Hippocrates is sending an insurance information request to the H. C. Payor Insurance Company for his patient, Adam A. Everyman. The response from the payor is shown in a more complete IN1 segment. However, it should be noted that in addition to the IN1 segment, this return information could have been placed in the NTE segment to serve as display data. This strategy would serve a broader community of diverse application systems that might have different levels of ability to process the record-formatted data.

MSH|^~\&|HIPPOCRATESMD|EWHIN|MSC|EWHIN|19940107155043||RQI^I01|HIPPOCRATESMD7888|P|2.9|||NE|AL<cr>

PRD|RP|HIPPOCRATES^HAROLD^^^DR^MD|1001 HEALTHCARE^DRIVE^ANN ARBOR^MI^99999| ^^^HIPPOCRATESMD&EWHIN^^^^^HIPPOCRATES MEDICAL CENTER|HIPPOCRATESMD7899<cr>

PRD|RT|HCIC||^^^MSC&EWHIN^^^^^H.C. PAYOR INSURANCE COMPANY<cr>

PID||| HL71001111111111^9^M10||EVERYMAN^ADAM^A||19600309||||||||||||444-33-3333<cr>

IN1|1|PPO|HC02|HCIC (MI State Code)|<cr>

MSH|^~\&|MSC|EWHIN|HIPPOCRATESMD|EWHIN|19940107155212||RPI^I01|MSC2112|P|2.9|||ER|ER<cr>

MSA|AA|HIPPOCRATESMD7888|ELIGIBILITY INFORMATION FOUND<cr>

PRD|RP|HIPPOCRATES^HAROLD^^^DR^MD|1001 HEALTHCARE DRIVE^^ANN ARBOR^MI^99999| ^^^HIPPOCRATESMD&EWHIN^^^^^HIPPOCRATES MEDICAL CENTER|HIPPOCRATESMD7899<cr>

PRD|RT|HCIC||^^^MSC&EWHIN^^^^^H.C. PAYOR INSURANCE COMPANY<cr>

PID|||HL71001111111111^9^M10||EVERYMAN^ADAM^A||19600301||||||||||||444-33-333CR>

IN1|1|PPO|HC02|HCIC (MI State Code)|5555 INSURERS CIRCLE ^^ANN ARBOR^MI^99999^USA|CHRISTOPHER CLERK|(855)555-1234|987654321||||19901101||||EVERYMAN^ADAM^A|1|19600309|N. 2222 HOME STREET^^ANN ARBOR^MI^99999^USA|||||||||||||||||444333555||||||01|M<cr>

=== RQA Message Using an I08 Event with an Immediate Response

When the attending physician decides to refer the patient for treatment to another healthcare provider, pre-authorization may be required by the payor. In the following RQA example, Dr. Blake is requesting the appropriate pre-authorization from H.C Payor Insurance Company for a colonoscopy on Adam Everyman. The request includes the diagnosis, in case it is a factor in the approval decision. As shown below, the immediate response indicates approval of the request that was made on 01/10/94 and that expires on 05/10/94. In actuality, most payors require some human intervention in the pre-authorization process and would probably not respond immediately.

MSH|^~\&|HIPPOCRATESMD|EWHIN|MSC|EWHIN|19940110105307||RQA^I08|HIPPOCRATESMD7898|P|2.9|||NE|AL<cr>

PRD|RP|HIPPOCRATES^HAROLD^^^DR^MD|1001 HEALTHCARE DRIVE^^ANN ARBOR^MI^99999| ^^^HIPPOCRATESMD&EWHIN^^^^^HIPPOCRATES MEDICAL CENTER|HIPPOCRATESMD7899<cr>

PRD|RT|HIIC||^^^MSC&EWHIN^^^^^H.C.PAYOR INSURANCE COMPANY<cr>

PID|||HL71001111111111^9^M10||EVERYMAN^ADAM^A||19600309||||||||||||444-33-3333<cr>

IN1|1|PPO|HC02|HCIC (MI State Code)|5555 INSURERS CIRCLE^^ANN ARBOR^MI^99999^USA|CHRISTOPHER CLERK|(855)555‑1234|(555)555-3002||||19901101||||EVERYMAN^ADAM^A|1|19600309|2222 HOME STREET^^ANN ARBOR^MI^99999^USA |||||||||||||||||444333555||||||01|M<cr>

DG1|1|I9|569.0|RECTAL POLYP|19940106103500|0<cr>

PR1|1|C4|45378|Colonoscopy|19940110105309|00<cr>

MSH|^~\&|MSC|EWHIN|HIPPOCRATESMD|EWHIN|19940110154812||RPA^I08|MSC2112|P|2.9|||ER|ER<cr>

MSA|AA|HIPPOCRATESMD7888<cr>

PRD|RP|HIPPOCRATES^HAROLD^^^DR^MD|1001 HEALTHCARE DRIVE^^ANN ARBOR^MI^99999| ^^^ HIPPOCRATESMD &EWHIN^^^^^HIPPOCRATES MEDICAL CENTER| HIPPOCRATESMD7899<cr>

PRD|RT|HIIC||^^^MSC&EWHIN^^^^^H.C.PAYOR INSURANCE COMPANY<cr>

PID|||HL71001111111111^9^M10||EVERYMAN^ADAM^A||19600301|||||||||||| HL71001111111111<cr>

IN1|1|PPO|HC02|HCIC (MI State Code)|5555 INSURERS CIRCLE^^ANN ARBOR^MI^99999^USA|CHRISTOPHER CLERK|(855)555‑1234|(555)555-3002||||19901101||||EVERYMAN^ADAM^A|1|19600309|2222 HOME STREET^^ANN ARBOR^MI^99999^USA|||||||||||||||||444555333||||||01|M<cr>

DG1|1|I9|569.0|RECTAL POLYP|19940106103500|0<cr>

PR1|1|C4|45378|Colonoscopy|19940110105309|00<cr>

AUT|PPO|HC02|HIIC (MI State Code)|19940110|19940510|HL71001111111111|175|1<cr>

=== RQA Message Using an I08 Event with a Deferred Response

In the following example of a pre-authorization request, the payor indicates his receipt of the request (a standard acknowledgment message), but defers issuing a pre-authorization to a later time. This response represents a more typical payor transaction sequence. Note the use of the "Accept Acknowledgment Type," requiring the receiving system to respond in all cases to receipt of the message.

MSH|^~\&|HIPPOCRATESMD|EWHIN|MSC|EWHIN|19940110105307||RQA^I08|HIPPOCRATES7898|P|2.9|||AL|AL<cr>

PRD|RP| HIPPOCRATES^HAROLD ^^^DR^MD|1001 HEALTHCARE DRIVE^^ANN ARBOR^MI^99999| ^^^HIPOOCRATES&EWHIN^^^^^HIPPOCRATES MEDICAL CENTER|HIPPOCRATESM7899<cr>

PRD|RT|HIIC||^^^MSC&EWHIN^^^^^H.C.PAYOR INSURANCE COMPANY<cr>

PID||| HL71001111111111^9^M10||EVERYMAN^ADAM^A||19600301|||||||||||| HL71001111111111<cr>

IN1|1|PPO|HC02|HCIC (MI State Code)|5555 INSURERS CIRCLE^^ANN ARBOR^MI^99999^USA|CHRISTOPHER CLERK|(855)555‑1234|(555)555-3002||||19901101||||EVERYMAN^ADAM^A|1|19600309|2222 HOME STREET^^ANN ARBOR^MI^99999^USA|||||||||||||||||444555333||||||01|M<cr>

PR1|1|C4|45378|Colonoscopy|19940110105309|00<cr>

MSH|^~\&|MSC|EWHIN|HIPPOCRATESMD|EWHIN|1994011015315||MCF|MSC2112|P|2.9|||ER|ER<cr>

MSA|AA|HIPPOCRATES7888<cr>

MSH|^~\&|MSC|EWHIN|HIPPOCRATESMD|EWHIN|19940111102304||RPA^I08|MSC2113|P|2.9|||ER|ER<cr>

MSA|AA|HIPPOCRATESM7888<cr>

PRD|RP| HIPPOCRATES^HAROLD ^^^DR^MD|1001 HEALTHCARE DRIVE^^ANN ARBOR^MI^99999| ^^^HIPOOCRATES&EWHIN^^^^^HIPPOCRATES MEDICAL CENTER|HIPPOCRATESM7899<cr><cr>

PRD|RT|WSIC||^^^MSC&EWHIN^^^^^H.C.PAYOR INSURANCE COMPANY<cr>

PID|||HL71001111111111^9^M10||EVERYMAN^ADAM^A ||19600301|||||||||||| HL71001111111111<cr>

IN1|1|PPO|HC02|HCIC (MI State Code)|5555 INSURERS CIRCLE^^ANN ARBOR^MI^99999^USA|CHRISTOPHER CLERK|(855)555‑1234|(555)555-3002||||19901101||||EVERYMAN^ADAM^A|1|19600309|2222 HOME STREET^^ANN ARBOR^MI^99999^USA|||||||||||||||||444555333||||||01|M<cr>

PR1|1|C4|45378|Colonoscopy|19940110105309|00<cr>

AUT|PPO|HC02|HIIC (MI State Code)|19940110|19940510|HL71001111111111|175|1<cr>

=== REF Message Using an I11 Event with an Immediate Response

Once pre-authorization has been received, the patient is referred to the referral provider. In the following example, Dr. Hippocrates is referring Adam Everyman to Dr. Tony Tum for a colonoscopy. The referral message includes the patient's demographic information, diagnosis and the pre-authorization information retrieved during the previous transaction. The dates contained in the pre-authorization segment (e.g., authorization date and authorization expiration date) pertain to the authorization, given by a payor, for a specified procedure. They are not intended to imply any kind of schedule request. Scheduling will be handled by the referral provider and the patient in a separate transaction. Not all referrals will require a detailed chain of response messages, so in this case, a simple acknowledgment in the form of an RPI is returned with a note from the referred-to provider.

MSH|^~\&|HIPPOCRATESMD|EWHIN|TUM|EWHIN|19940111113142||REF^I11|HIPPOCRATESM7899|P|2.9|||NE|AL<cr>

RF1||R|MED|RP|O|REF4502|19940111|19940510|19940111<cr>

PRD|RP|HIPPOCRATES^HAROLD^^^DR^MD|1001 HEALTHCARE DRIVE^^ANN ARBOR^MI^99999| ^^^HIPPOCRATESMD&EWHIN^^^^^HIPPOCRATES MEDICAL CENTER|HIPPOCRATES7899<cr>

CTD|PR|ENTER^ELLEN|1001 HEALTHCARE DRIVE^^ANN ARBOR^MI^99999^USA^|^^^HIPPOCRATESMD&EWHIN^^^^^HIPPOCRATES MEDICAL CENTER<cr>

PRD|RT|TUM^TONY^^^DR||^^^JIME&EWHIN^^^^^TUM AND TUMOR||||531886<cr>

PID|||HL71001111111111^9^M10||EVERYMAN^ADAM^A ||19600309|M||C|2222 HOME STREET^^ANN ARBOR^MI^99999^USA|SPO|(555)555-2004|ENGL|M|M||HL71001111111111EVERYMAN*3-444-555^MI<cr>

NK1|1|EVERYMAN^BETTERHALF^W|2|2222 HOME STREET^^ANN ARBOR^MI^99999^USA|(555)555-2004<cr>

GT1|1||EVERYMAN^ADAM^A||2222 HOME STREET^^ANN ARBOR^MI^99999^USA|(555)4555-2004|(555)555-2004|19600309|M||1|402941703||||CONTACT*CARRIE|||456789|01<cr>

IN1|1|PPO|HC02|HCIC (MI State Code)|5555 INSURERS CIRCLE^^ANN ARBOR^MI^99999^USA|CHRISTOPHER CLERK|(855)555‑1234|(555)555-3002||||19901101||||EVERYMAN^ADAM^A|1|19600309|2222 HOME STREET^^ANN ARBOR^MI^99999^USA|||||||||||||||||444555333||||||01|M<cr>

ACC|19940105125700|WR|ENTER*ELLEN<<cr>

DG1|1|I9|569.0|RECTAL POLYP|19940106103500|0<cr>

PR1|1|C4|45378|Colonoscopy|19940110105309|00<cr>

AUT|PPO|WA02|HCIC (MI State Code)|19940110|19940510|123456789|175|1<cr>

MSH|^~\&|TUM|EWHIN|HIPPOCRATESMD|EWHIN|19940111152401||RRI^I11|TUM1123|P|2.9|||ER|ER<cr>

MSA|AA|TUMM7900<cr>

RF1|A|R|MED|RP|O|REF4502|19940111|19940510|19940111<cr>

PRD|RP|TUM^TONY^^^DR^MD|1031 HEALTHCARE DRIVE^^ANN ARBOR^MI^99999| ^^^TUMMD&EWHIN^^^^^HIPPOCRATES MEDICAL CENTER|TUMMT7900<cr>

CTD|PR|ENTER^ELLEN|1021 HEALTHCARE DRIVE^^ANN ARBOR^MI^99999|^^^TUMTMD&EWHIN^^^^^TUM MEDICAL CENTER<cr>

PRD|RT|TUM^TONY^^^DR||^^^TUM&EWHIN^^^^^TUM AND TUMOR||||531886<cr>

PID|||HL71001111111111^9^M10||EVERYMAN^ADAM^A ||19600309|M||C|2222 HOME STREET^^ANN ARBOR^MI^99999^USA|SPO|(555)555-2004|ENGL|M|M||HL71001111111111EVERYMAN*3-444-555^MI<cr>

DG1|1|I9|569.0|RECTAL POLYP|19940106103500|0<cr>

PR1|1|C4|45378|Colonoscopy|19940111141509|00<cr>

NTE|||Patient is doing well.~Full recovery expected.<cr>

=== REF Message Using an I11 Event with a Deferred Response

The following example demonstrates the ability of the referral provider to return a series of responses. For most referrals, multiple responses will be returned because referrals may contain multiple requested procedures that may be performed over a period of time. The referral provider determines the completion of this chain of messages and indicates that designation in the following example by setting the "Processed" flag in the MSA segment. This procedure will probably vary from network to network.

MSH|^~\&|TUMMD|EWHIN|HIPPOCRATESMD|EWHIN|19940111113142||REF^I11|TUMMM7899|P|2.9|||AL|AL<cr>

RF1||R|MED|RP|O|REF4502|19940111|19940510|19940111<cr>

PRD|RP|TUM^TONY^^^DR^MD|1031 HEALTHCARE DRIVE^^ANN ARBOR^MI^99999| ^^^TUMMD&EWHIN^^^^^HIPPOCRATES MEDICAL CENTER|TUMMT7900<cr>

CTD|PR|ENTER^ELLEN|1021 HEALTHCARE DRIVE^^ANN ARBOR^MI^99999|^^^TUMTMD&EWHIN^^^^^TUM MEDICAL CENTER<cr>

PRD|RT|TUM^TONY^^^DR||^^^TUM&EWHIN^^^^^TUM AND TUMOR||||531886<cr>

PID|||HL71001111111111^9^M10||EVERYMAN^ADAM^A ||19600309|M||C|2222 HOME STREET^^ANN ARBOR^MI^99999^USA|SPO|(555)555-2004|ENGL|M|M||HL71001111111111EVERYMAN*3-444-555^MI<cr>

NK1|1|EVERYMAN^BETTERHALF^W|2|2222 HOME STREET^^ANN ARBOR^MI^99999^USA|(555)555-2004<cr>

GT1|1||EVERYMAN^ADAM^A||2222 HOME STREET^^ANN ARBOR^MI^99999^USA|(555)4555-2004|(555)555-2004|19600309|M||1|402941703||||CONTACT*CARRIE|||456789|01<cr>

IN1|1|PPO|HC02|HCIC (MI State Code)|5555 INSURERS CIRCLE^^ANN ARBOR^MI^99999^USA|CHRISTOPHER CLERK|(855)555‑1234|(555)555-3002||||19901101||||EVERYMAN^ADAM^A|1|19600309|2222 HOME STREET^^ANN ARBOR^MI^99999^USA|||||||||||||||||444555333||||||01|M<cr>

ACC|19940105125700|WR|ENTER*ELLEN<cr>

DG1|1|I9|569.0|RECTAL POLYP|19940106103500|0<cr>

PR1|1|C4|45378|Colonoscopy|19940110105309|00<cr>

AUT|PPO|HC02|HCIC (MI State Code)|19940110|19940510|123456789|175|1<cr>

MSH|^~\&|TUMMD|EWHIN|HIPPOCRATESMD|EWHIN|19940111154812||MCF|TUMT1123|P|2.9|||ER|ER<cr>

MSA|AA|TUMM7899<cr>

MSH|^~\&|TUM|EWHIN|HIPPOCRATESMD|EWHIN|19940112152401||RRI^I11|TUMTE1124|P|2.9|||ER|ER<cr>

MSA|AA|HIPPOCRATESM7899<cr>

RF1|A|R|MED|RP|O|REF4502|19940111|19940510|19940111<cr>

PRD|RP|HIPPOCRATES^HAROLD^^^DR^MD|1001 HEALTHCARE DRIVE^^ANN ARBOR^MI^99999|^^^HIPPOCRATESMD&EWHIN^^^^^HIPPOCRATES MEDICAL CENTER|HIPPOCRATESM7899<cr>

CTD|PR|ENTER^ELLEN|1001 HEALTHCARE DRIVE^^ANN ARBOR^MI^99999|^^^HIPPOCRATESMD&EWHIN^^^^^HIPPOCRATES MEDICAL CENTER<cr>

PRD|RP|TUM^TONY^^^DR^MD|1031 HEALTHCARE DRIVE^^ANN ARBOR^MI^99999| ^^^TUMMD&EWHIN^^^^^HIPPOCRATES MEDICAL CENTER|TUMMT7900<cr>

PID|||HL71001111111111^9^M10||EVERYMAN^ADAM^A ||19600309|M||C|2222 HOME STREET^^ANN ARBOR^MI^99999^USA|SPO|(555)555-2004|ENGL|M|M||HL71001111111111EVERYMAN*3-444-555^MI<cr>

DG1|1|I9|569.0|RECTAL POLYP|19940106103500|0<cr>

PR1|1|C4|45378|Colonoscopy|19940111141509|00<cr>

NTE|||Patient is doing well.~Full recovery expected.<cr>

