= General Use Cases / Background
:render_as: Level4
:v291_section: 11.2.1+; 11.2.2+

== Patient Referral and Responses

When a patient is referred by one healthcare entity (e.g., a primary care provider) to another (e.g., a specialist or lab) or when a patient inquiry is made between two separate entities, little is known about the information each party requires to identify or codify the patient. The receiving entity may have no knowledge of the patient and may require a full set of demographics, subscriber and billing information, eligibility/coverage information, pre-authorization information, and/or clinical data to process the referral. If the receiving entity already has a record of the patient, the precise requirements for identifying that patient record will vary greatly from one entity to another. The existing record of a patient residing in the database of a specialist, a lab, or a hospital may require updating with more current information. In addition, providers receiving a referral often require detailed information about the provider making the referral, such as a physician's name and address.

For example, a primary care provider making a referral may need to obtain insurance information or pre-authorization from a payor prior to making a referral. Getting this information requires an inquiry and a response between the primary care provider and the payor. In addition, the primary care provider may request results from a lab to accompany the referral. Getting these results may require an inquiry and a response between the primary care provider and the lab. The information could then be incorporated into a referral sent from the primary care provider to the specialist. As the referral is processed, requested procedures are performed, the results are observed, and the relevant data must be returned to the primary care provider. Such a response may frequently take the form of multiple responses as results become available.

The message set that encompasses these transactions includes the referral (REF), requests for information (RQA, RQC, RQP, RQI) and the returned patient information (RCI, RCL, RPA, RPI, RPL, RRI). The referral message originates a transaction and a return patient information message concludes the transaction. At least one RPA/RPI is required to complete a patient referral or a patient request transaction, although multiple RPI messages may be returned in response to a single REF message. The segments used in the REF, RQA, RQI, RQP, RRI, RPH, RCI, RCL, RPA and RPI messages encompass information about patient, guarantor and next of kin demographics, eligibility/coverage information, accident, diagnosis, requested procedures, payor pre-authorization, notes, and referring and consulting provider data.

=== Patient referral

There are clear distinctions between a referral and an order. An order is almost always an intra-enterprise transaction and represents a request from a patient's active provider to supporting providers for clearly defined services and/or results. While the supporting provider may exercise great discretion in the performance of an order, overall responsibility for the patient's plan of treatment remains with the ordering provider. As such, the ordering provider retains significant control authority for the order and can, after the fact, cause the order to be canceled, reinstated, etc. Additionally, detailed results produced by the supporting provider are always reported back to the ordering provider, who remains ultimately responsible for evaluating their value and relevance. A referral, on the other hand, can be either an intra- or an inter-enterprise transaction and represents not only a request for additional provider support but also a transfer of a portion or all of the responsibility for the patient's plan of treatment. Once the referral is made, the referring provider, during the transfer period, retains almost no control of any resulting actions. The referred-to provider becomes responsible for placing any additional orders and for evaluating the value and relevance of any results, which may or may not be automatically passed back to the referring provider. A referred-to provider may, in turn, also become a referring provider.

A referral message is used to support transactions related to the referral of a patient from one healthcare provider to another. This kind of message will be particularly useful from the perspective of a primary care provider referring a patient to a specialist. However, the application of the message should not be limited to this model. For example, a referral may be as simple as a physician sending a patient to another physician for a consultation or it may be as complex as a primary care provider sending a patient to a specialist for specific medical procedures to be performed and attaching the payor authorizations for those requested procedures as well as the relevant clinical information on the patient's case.

In a community model, stringent security requirements will need to be met when dealing with the release of clinical information. This message set facilitates the proper qualification of requests because the message packet will contain all the data required by any application in the community, including the necessary patient demographic information and the proper identification of the party requesting the information.

=== Responding to a patient referral

=== Communicating Collaborative Care of a Patient

When providers collaborate in the sharing of patient care there can be many types of communications involved, and the expectations, roles and responsibilities may not always be clear and explicit; they may vary in different jurisdictions or work practice environments.

The use of HL7 Version 2.x in clinical messaging has involved the use of segments in ways for which they were not originally intended, as well as the development of the REL segment to express important relationships between clinical data components. Such use has also necessitated the introduction of mood codes to allow for the richer representation of intent, purpose, timing, and other event contingencies that such concepts required. When these extensions are applied to segments in messages which predate them there is the risk that a message generated by a system compliant with an earlier release could be misinterpreted by a system which interprets the segments in the wider context. The approach to this has been to constrain the use of the enhancements to these segments to new messages, or to newer versions of existing messages. The REF message has been in releases which pre-date the v2.6 clinical enhancements and its limitations in this regard, together with the need for a range of new Collaborative Care interactions, have led to the need for the Collaborative Care Message. Being developed to use the clinical v2.6 enhancements from the outset, the collaborative care messages do not need these versioning constraints around their use.

== Application Roles and Data Process

=== Application roles

This Standard assumes that there are four roles that an application can take on: a referring or referred-by provider application role, a referred-to provider application role, a querying application role, and an auxiliary application role. These application roles define the interactions an application will have with other applications in the messaging environment. In many environments, any single application may take on more than one application role.

This Standard's definition of application roles does not intend to define or limit the functionality of specific products developed by vendors of such applications. Instead, this information is provided to help define the model used to develop this Standard, and to provide an unambiguous way for applications to communicate with each other.

=== The referring provider application role

A referring provider application requests the services of another healthcare provider (a referred-to provider) application. There may or may not be any association between the referring provider application and the receiving entity. Although in most cases a referral environment will be inter-enterprise in nature, it is not limited to that model and applies to intra-enterprise situations also. Because the referring provider application cannot exert any control over the referred-to provider application, it must send requests to modify the status of the referred-to provider application. The referring provider application will often assume an auxiliary application role once a patient has been accepted by another application. Once this happens, the referring provider application may receive unsolicited status updates from the referred-to provider application concerning the care of a patient.

The analog of a referring provider application in a non‑automated environment might be a primary care provider diagnosing a patient with a problem that must in turn be referred to a specialist for a service. The primary care provider would contact the specialist and refer the patient into his care. Often, the specialist may not receive the patient into his care, preferring instead to refer the patient to another healthcare provider. The referring provider will indicate the diagnosis and any requested services, and the specialist to whom the patient is referred will indicate whether the referral will be accepted as specified. Once a patient referral has been accepted by the specialist, the specialist may send out updates to the primary care provider concerning the status of the patient as regards any tests performed, their outcomes, etc.

=== The referred-to provider application role

A referred-to provider application, in the referral model, is one that performs one or more services requested by another healthcare provider (referring provider). In other words, a referred-to provider application exerts control over a certain set of services and defines the availability of those services. Because of this control, no other application has the ability to accept, reject, or otherwise modify a referral accepted by a particular referred-to provider application.

Other applications can, on the other hand, make requests to modify the status of an accepted referral "owned by" the referred-to provider application. The referred-to provider application either grants or denies requests for information, or otherwise modifies the referrals for the services over which it exerts control.

Finally, the referred-to provider application also provides information about the referral encounter to other applications. The reasons that an application may be interested in receiving such information are varied. An application may have previously requested the status of the referral encounter, or it may simply be interested in the information for its own clinical reporting or statistical purposes. There are two methods whereby the referred-to provider applications disseminate this information: by issuing unsolicited information messages to auxiliary applications, or by responding to queries made by querying applications.

The analog of a referred-to provider application in a non‑automated environment might be a specialist such as a cardiologist. A patient does not generally go to a cardiologist for routine health care. Instead, a patient generally goes to a primary care provider, who may diagnose the patient with a heart ailment and refer that patient to a cardiologist. The cardiologist would review the information provided with the referral request and determine whether or not to accept the patient into his care. Once the cardiologist accepts the patient, anyone needing information on the status of the patient must then make requests to the cardiologist. In addition, the cardiologist may forward unsolicited information regarding the treatment of the patient back to the primary care provider. Once the cardiologist accepts the referred patient, he/she may determine that additional information regarding the patient is needed. It will often take the role of a querying application by sending a query message to the patient's primary care provider and requesting additional information on demographics, insurance information, laboratory test results, etc.

=== The querying application role

A querying application neither exerts control over, nor requests changes to a referral. Rather than accepting unsolicited information about referrals, as does an auxiliary application, the querying application actively solicits this information using a query mechanism. It will, in general, be driven by an entity seeking information about a referral such as a referring provider application or an entity seeking information about a referred patient such as a referred-to provider application. The information that the querying application receives is valid only at the exact time that the query results are generated by the provider applications. Changes made to the referral or the referred patient's status after the query results have been returned are not communicated to the querying application until it issues another query transaction.

The analog of a querying application in a non‑automated environment might be a primary care provider seeking information about a specific patient who has been referred to a specialist. For example, a patient may have been referred to a specialist in order that a specific test be performed, following which, the patient would return to the primary care provider. If the specialist has not forwarded information regarding the testing procedures for the patient to the primary care provider, the primary care provider would then query the specialist for the outcome of those procedures. Likewise, if a specialist received a referred patient without the preliminary diagnoses of test results, he/she might in turn query the primary care provider for the information leading to the diagnoses and subsequent referral.

=== The auxiliary application role

Like querying applications, an auxiliary application neither exerts control over nor requests changes to a referral or a referred patient. They, too, are only concerned with gathering information about a particular referral. An auxiliary application is considered an "interested third‑party," in that it is interested in any changes to a particular referral or referred patient, but has no interest in changing it or controlling it in any way. An auxiliary application passively collects information by receiving unsolicited updates from a provider application.

The analog of an auxiliary application in a non‑automated environment might be any person receiving reports containing referral information. For example, an insurance company may need information about the activities a patient experiences during specific referral encounters. Primary care providers may need to forward information regarding all referred patients to a payor organization.

In turn, a primary care provider may have the ability to track electronically a patient's medical record. The provider would then be very interested in receiving any information regarding a patient referred to a specialist.

=== Application roles in a messaging environment

In a messaging environment, these four application roles communicate using specific kinds of messages and trigger events. The following figure illustrates the relationships between these application roles in a messaging environment:

Figure 11‑1. Application role messaging relationships

image:extracted-media/media/image1.wmf[extracted-media/media/image1]

