= Message - E03 Query HealthCare Services Invoice Status
:render_as: Message Page
:v291_section: 16.3.3; 16.3.4

This message is used to query the status of a HealthCare Services Invoice. There are 3 types of queries handled by this message: 1) a specific Invoice, 2) a specific Product/Service Group or 3) a specific Product/Service Line Item. If a Provider wants to obtain information on a group of invoices (e.g., submitted in a date range), each individual Invoice must be queried.

This message may also be used to query an Invoice submitted at another Network Application ID and Network Facility ID, as long as sufficient identification information is provided to qualify the request and requestor. These are noted as Processing Rules for this message.

Note that the response to this query has the same content as an EHC^E10 – Edit/Adjudication Results message.

Processing Rules:

{empty}1) The Provider Application and the Payer Application must uniquely identify each Invoice, Product/Service Group, Product/Service Line Item and Adjustment. +

These numbers appear as a pair on the IVC, PSG, PSL and ADJ segments and must be echoed on any subsequent interactions for the Invoice, group or line item between the Provider Application and Payer Application.

{empty}2) The Provider Application and/or Payer Application may also supply a tracking number for each Product/Service Line Item it processes, specified as the Provider Tracking Number or Payer Tracking Number. +

The Provider Tracking Number and Payer Tracking Number must be echoed on any subsequent interactions for the Product/Service Line Item between the Provider Application and Payer Application.

{empty}3) A unique query identifier (Query Tag on QPD) must be generated for each query. +

Provider Invoice Number + Payer Invoice Number + Product/Service Line Item Number on input message must exist on Payer Application's database and must point to the same Product/Service Line Item, otherwise an error must be generated (mismatched Invoice and/or Product/Service Line Item).

{empty}4) To query an Invoice, the following fields must be supplied and must match the original Invoice submitted: +

QPD.Sending Organization +

QPD.Provider Organization +

QPD.Invoice Amount +

QPD.Provider Invoice Number +

QPD.Payer Invoice Number +

QPD.Payee Identification List

{empty}5) To query a Product/Service Group within an Invoice, the following fields must be supplied and must match the original Invoice submitted: +

QPD.Sending Organization +

QPD.Provider Organization +

QPD.Invoice Amount +

QPD.Provider Invoice Number +

QPD.Payer Invoice Number +

QPD.Payee Identification List +

QPD.Provider Product/Service Group Number +

QPD.Payer Product/Service Group Number

{empty}6) To query a Product/Service Line Item within an Invoice, the following fields must be supplied and must match the original Invoice submitted: +

QPD.Sending Organization +

QPD.Provider Organization +

QPD.Invoice Amount +

QPD.Provider Invoice Number +

QPD.Payer Invoice Number +

QPD.Payee Identification List +

QPD.Provider Product/Service Group Number +

QPD.Payer Product/Service Group Number +

QPD.Provider Product/Service Line Item Number +

QPD.Payer Product/Service Line Item Number

QBP^E03^QBP_E03: Query HealthCare Services Invoice

[width="100%",cols="33%,47%,9%,11%",options="header",]

|===

|Segments |Description |Status |Chapter

|MSH |Message Header | |2

|[ \{ SFT } ] |Secondary Header | |2

|[ \{ UAC } ] |User Authentication Credential | |2

|< |--- QUERY_INFORMATION begin | |

|QPD |Query Parameter Definition | |5

|RCP |Response Control Parameter | |5

|> |--- QUERY_INFORMATION end | |

|===

[width="99%",cols="18%,24%,6%,16%,18%,18%",options="header",]

|===

|Acknowledgement Choreography | | | | |

|QBP^E03^QBP_E03 | | | | |

|Field name |Field Value: Original mode |Field value: Enhanced mode | | |

|MSH-15 |Blank |NE |AL, SU, ER |NE |AL, SU, ER

|MSH-16 |Blank |NE |NE |AL, SU, ER |AL, SU, ER

|Immediate Ack |- |- |ACK^E03^ACK |- |ACK^E03^ACK

|Application Ack |RSP^E03^RSP_E03 |- |- |RSP^E03^RSP_E03 |RSP^E03^RSP_E03

|===

This message is used to respond to a QPB^E03 – Query HealthCare Services Invoice. It provides Invoice and invoice processing information to a Provider.

A QBP^E03 – Query HealthCare Services Invoice can be used to query against an Invoice or a specific Product/Service Line Item in an Invoice. The same response message, RSP^E03 – HealthCare Services Invoice Query Response, is used for both types of query.

Processing Rules:

{empty}1) Provider Invoice Number + Payer Invoice Number + Product/Service Line Item Number on input message must exist on Payer Application's database and must point to the same Product/Service Line Item, otherwise an error must be generated (mismatched Invoice and/or Product/Service Line Item).

{empty}2) Sending Organization and Sending Application on input message must be the same as the Sending Organization and Sending Application from the original Invoice (submitted via the EHC^E01 – Submit HealthCare Services Invoice message) for the specified Invoice being queried.

{empty}3) A unique query identifier (Query Tag on QPD) must be generated for each query.

RSP^E03^RSP_E03: HealthCare Services Invoice Query Response

[width="100%",cols="33%,47%,9%,11%",options="header",]

|===

|Segments |Description |Status |Chapter

|MSH |Message Header | |2

|[ \{ SFT } ] |Software | |2

|[ \{ UAC } ] |User Authentication Credential | |2

|MSA |Message Acknowledgement | |2

|[ \{ ERR } ] |Error | |2

|< |--- QUERY_ACK_IPR begin | |

|QAK |Query Acknowledgement | |

|QPD |Query Parameter Definition | |

|[ \{ IPR} ] |Invoice Processing Results | |16

|> |--- QUERY_ACK_IPR end | |

|===

[width="100%",cols="23%,35%,10%,32%",options="header",]

|===

|Acknowledgement Choreography | | |

|RSP^E03^RSP_E03 | | |

|Field name |Field Value: Original mode |Field value: Enhanced mode |

|MSH-15 |Blank |NE |AL, SU, ER

|MSH-16 |Blank |NE |NE

|Immediate Ack |- |- |ACK^E03^ACK

|Application Ack |- |- |-

|===

[message-tabs, ["QBP^E03^QBP_E03", "QBP Interaction", "ACK^E03^ACK", "ACK Interaction", "RSP^E03^RSP_E03", "RSP Interaction"]]

