= ECD
:render_as: Level3
:v291_section: 13.3.5+

== ECD - Equipment Command Segment 

The equipment command segment contains the information required to notify the receiving component what is to happen.

HL7 Attribute Table – ECD[#ECD .anchor]#### – Equipment Command

[width="100%",cols="14%,6%,7%,6%,6%,6%,7%,7%,41%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |OPT |RP/# |TBL# |ITEM # |ELEMENT NAME

|1 | |10= |NM |R | | |01390 |Reference Command Number

|2 | | |CWE |R | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70368[0368] |01391 |Remote Control Command

|3 |1..1 | |ID |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70136[0136] |01392 |Response Required

|4 | | | |W | | |01393 |Requested Completion Time

|5 | | |TX |O |Y | |01394 |Parameters

|===

=== ECD-1 Reference Command Number (NM) 01390

=== ECD-2 Remote Control Command (CWE) 01391

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: This field identifies the command that the component is to initiate. Refer to _file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70368[User-defined Table 0368 – Remote Control Comman]d_ in Chapter 2C, Code Tables, for valid values. Refer to LECIS standard for details.

=== ECD-3 Response Required (ID) 01392

=== ECD-4 Requested Completion Time 01393

=== ECD-5 Parameters (TX) 01394

Definition: This field identifies the parameters of the command (if they are not included in a separate segment(s)).

*Note:* Elements of this segment (or other elements not defined here) may be required for certain vendor-specific equipment such as centrifuges, aliquoters, sorters, uncappers, recappers, automated storage units, etc.

