= ILT
:render_as: Level3
:v291_section: 17.5.8+

== ILT – Material Lot Segment

The Material Lot segment (ILT) contains material information specific to a lot within an inventory location associated with the item in the IVT segment. This segment is similar to the IIM segment used with the limited inventory item master message.

*Note:* Note that on-hand quantities do NOT refer to a continuously updated quantity. The expectation is for periodic physical inventory.

HL7 Attribute Table – ILT – Material Lot

[width="100%",cols="14%,6%,7%,6%,6%,6%,7%,7%,41%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |OPT |RP/# |TBL# |ITEM# |ELEMENT NAME

|1 |1..4 | |SI |R | | |02086 |Set Id - ILT

|2 | |250= |ST |R | | |01800 |Inventory Lot Number

|3 | | |DTM |O | | |01801 |Inventory Expiration Date

|4 | | |DTM |O | | |01804 |Inventory Received Date

|5 | |12# |NM |O | | |01805 |Inventory Received Quantity

|6 | | |CWE |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70818[0818] |01806 |Inventory Received Quantity Unit

|7 | | |MO |O | | |01807 |Inventory Received Item Cost

|8 | | |DTM |O | | |01808 |Inventory On Hand Date

|9 | |12# |NM |O | | |01809 |Inventory On Hand Quantity

|10 | | |CWE |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70818[0818] |01810 |Inventory On Hand Quantity Unit

|===

=== ILT-1 Set ID – ILT (SI) 02086

=== ILT-2 Inventory Lot Number (ST) 01800

Definition: This field contains the lot number of the service item in inventory.

____

*Note:* The lot number is the number printed on the label attached to the item or container holding the substance. If the substance is a vaccine, for example, and a diluent is required, a lot number may appear on the vial containing the diluent; however, any such identifier associated with a diluent is not the identifier of interest. The substance lot number should be reported, not that of the diluent.

____

Note:

=== ILT-3 Inventory Expiration Date (DTM) 01801

Definition: This field contains the expiration date of the service item in inventory.

____

*Note:* Expiration date does not always have a "day" component; therefore, such a date may be transmitted as YYYYMM.

____

=== ILT-4 Inventory Received Date (DTM) 01804

=== ILT-5 Inventory Received Quantity (NM) 01805

=== ILT-6 Inventory Received Quantity Unit (CWE) 01806

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: This field specifies the unit for the _Inventory Received Quantity_. See file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70818[_User-defined Table 0818 – Package_] as described in _PKG-2 Packaging Units_ and as presented in Chapter 2C, Code Tables, for suggested values.

=== ILT-7 Inventory Received Item Cost (MO) 01807

Components: <Quantity (NM)> ^ <Denomination (ID)>

Definition: This field contains the per-unit cost of the inventory item at the time of receipt. _ILT-6 Inventory Received Quantity Unit_ field specifies the per-unit basis of this field.

=== ILT-8 Inventory on Hand Date (DTM) 01808

=== ILT-9 Inventory on Hand Quantity (NM) 01809

=== ILT-10 Inventory on Hand Quantity Unit (CWE) 01810

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: This field contains the quantity of this inventory item that was available for issue/use as of the date specified in _ILT-8 Inventory on Hand Date_ field. No adjustment has been made for subsequent use. See file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70818[_User-defined Table 0818 – Package_] as described in _PKG-2 Packaging Units_ and as presented in Chapter 2C, Code Tables, for suggested values.

