= IPR
:render_as: Level3
:v291_section: 16.4.9+

== IPR – Invoice Processing Results Segment

The Invoice Processing Results (IPR) segment provides summary information about an adjudicated Product/Service Group or Product/Service Line Item.

HL7 Attribute Table – IPR – Invoice Processing Results

[width="100%",cols="14%,6%,7%,6%,6%,6%,7%,7%,41%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |R/O |RP/# |TBL# |ITEM# |ELEMENT NAME

|1 | | |EI |R | | |02030 |IPR Identifier

|2 | | |EI |R | | |02031 |Provider Cross Reference Identifier

|3 | | |EI |R | | |02032 |Payer Cross Reference Identifier

|4 | | |CWE |R | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70571[0571] |02033 |IPR Status

|5 | | |DTM |R | | |02034 |IPR Date/Time

|6 | | |CP |O | | |02035 |Adjudicated/Paid Amount

|7 | | |DTM |O | | |02036 |Expected Payment Date/Time

|8 | |10= |ST |R | | |02037 |IPR Checksum

|===

=== IPR-1 IPR Identifier (EI) 02030

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: Unique IPR Number assigned by the Payer Application.

=== IPR-2 Provider Cross Reference Identifier (EI) 02031

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: Cross reference to Provider Product/Service Group Number or Provider Product/Service Line Item Number from original Invoice.

=== IPR-3 Payer Cross Reference Identifier (EI) 02032

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: Cross reference to Payer Product/Service Group Number or Payer Product/Service Line Item Number from original Invoice.

=== IPR-4 IPR Status (CWE) 02033

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: Processing status for the Product/Service Group (if Adjudicate as Group = "Y") or Product/Service Line Item. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70571[_User-defined Table 0571 – Invoice Processing Results Status_] in Chapter 2C, Code Tables, for suggested values.

The referenced status codes represent status codes for an IPR (Invoice Processing Result).

=== IPR-5 IPR Date/Time (DTM) 02034

=== IPR-6 Adjudicated/Paid Amount (CP) 02035

Components: <Price (MO)> ^ <Price Type (ID)> ^ <From Value (NM)> ^ <To Value (NM)> ^ <Range Units (CWE)> ^ <Range Type (ID)>

Subcomponents for Price (MO): <Quantity (NM)> & <Denomination (ID)>

Subcomponents for Range Units (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Definition: Adjudicated Amount for the Product/Service Group or Product/Service Line Item, which could be 0 = sum of all Payer adjustments (Adjustment Amount on ADJ).

=== IPR-7 Expected Payment Date/Time (DTM) 02036

=== IPR-8 IPR Checksum (ST) 02037

Definition: Conditional, if Status = "Accepted", then Required, else Not Permitted.

The field contains a checksum generated by the first Payer (referenced by Payer Organization in the IVC Segment) to ensure that the contents of IPR have not been altered before sending to subsequent Payers.

