= NSC
:render_as: Level3
:v291_section: 14.4.2+

== NSC – Application Status Change Segment

The NSC segment is used to inform (NMR query response) or announce (NMD unsolicited update) the start‑up, shut‑down, and/or migration (to a different CPU or file‑server/file‑system) of a particular application.

*Usage Notes:* Fields 2-9. These are not applicable ("n/a") when the type of change being requested or reported is start-up or shut-down. If the change is of type "M", at least one of fields 2-5 must be different from its corresponding field in range 6-9.

Fields 4-5, 8-9. See definitions for the MSH, message header segment, in Chapter 2, "Control Section," for fields 3-4, for system and facility. "Application" is available for interfacing with lower level protocols. "Facility" is entirely site-defined.

Fields 2-3, 6-7: entirely site-defined.

HL7 Attribute Table – NSC[#NSC .anchor]#### – Application Status Change

[width="100%",cols="14%,6%,7%,6%,6%,6%,7%,7%,41%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |R/O |RP/# |TBL# |ITEM# |ELEMENT NAME

|1 | | |CWE |R | |E:\\V2\\v2.9 final Nov from Frank\\V29_CH02C_Tables.docx#HL70409[0409] |01188 |Application Change Type

|2 | | |ST |O | | |01189 |Current CPU

|3 | | |ST |O | | |01190 |Current Fileserver

|4 | | |HD |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70361[0361] |01191 |Current Application

|5 | | |HD |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70362[0362] |01192 |Current Facility

|6 | | |ST |O | | |01193 |New CPU

|7 | | |ST |O | | |01194 |New Fileserver

|8 | | |HD |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70361[0361] |01195 |New Application

|9 | | |HD |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70362[0362] |01196 |New Facility

|===

=== NSC-1 Application Change Type (CWE) 01188 

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: This field contains the type of change being requested (if NMR query) or announced (if NMD unsolicited update). Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70409[_User-Defined Table 0409 - Application Change Type_] in Chapter 2C, Code Tables, for suggested values. It is assumed that "new" version starts up with no loss or duplication of data as old one is shutting down (if possible).

=== NSC-2 Current CPU (ST) 01189

=== NSC-3 Current Fileserver (ST) 01190

=== NSC-4 Current Application (HD) 01191 

Components: <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: This field contains a site-specific name used to identify the "current" application process for interfacing with lower level protocols. To be used in conjunction with the sending/receiving system and facility values in the MSH. Entirely site-defined. file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70361[_User-defined Table 0361-Sending/Receiving Application_] is used as the user-defined table of values for the first component.

*Note:* By site agreement, implementors may continue to use file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70300[_User-defined Table 0300 – Namespace ID_] for the first component.

=== NSC-5 Current Facility (HD) 01192 

Components: <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: This field contains a site-specific name for the current facility used by this application. To be used in conjunction with the values for the sending/receiving system and facility values in the MSH. This field further describes the current application, _NSC-5 Current Application_. With the promotion of this field to an HD data type, the usage has been broadened to include not just the current facility but other organizational entities, such as: a) the organizational entity responsible for current application; b) the responsible unit; c) a product or vendor's identifier, etc. Entirely site‑defined. file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70362[_User-defined Table 0362 – Sending/Receiving Facility_] is used as the HL7 identifier for the user-defined table of values for the first component.

____

*Note:* By site agreement, implementors may continue to use file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70300[_User-defined Table 0300 – Namespace ID_] for the first component.

____

=== NSC-6 New CPU (ST) 01193 

=== NSC-7 New Fileserver (ST) 01194 

=== NSC-8 New Application (HD) 01195

Components: <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: This field contains a site-specific name used to identify "new" application processes for interfacing with lower level protocols. To be used in conjunction with the sending/receiving system and facility values in the MSH. Entirely site-defined. file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70361[_User-defined Table 0361-Sending/Receiving Application_] is used as the user-defined table of values for the first component.

____

*Note:* By site agreement, implementors may continue to use file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70300[_User-defined Table 0300 – Namespace ID_] for the first component.

____

=== NSC-9 New Facility (HD) 01196

Components: <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: This field contains a site-specific name for the new facility used by this application. To be used in conjunction with the values for the sending/receiving system and facility values in the MSH.

This field further describes the new application, _NSC-8 New Application_. With the promotion of this field to an HD data type, the usage has been broadened to include not just the new facility but other organizational entities, such as: a) the organizational entity responsible for new application; b) the responsible unit; c) a product or vendor's identifier, etc. Entirely site‑defined. file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70362[_User-defined Table 0362 – Sending/Receiving Facility_] is used as the HL7 identifier for the user-defined table of values for the first component.

____

*Note:* By site agreement, implementors may continue to use file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70300[_User-defined Table 0300 – Namespace ID_] for the first component.

____

