= PSG
:render_as: Level3
:v291_section: 16.4.5+

== PSG – Product/Service Group Segment

The Product/Service Group segment is used to form a logical grouping of Product/Service Line Items, Patients and Response Summaries for a particular Invoice. For example, a Product/Service Group can be used to group all Product/Service Line Items that must be adjudicated as a group in order to be paid.

HL7 Attribute Table – PSG – Product/Service Group

[width="100%",cols="14%,6%,7%,6%,6%,6%,7%,7%,41%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |R/O |RP/# |TBL# |ITEM# |ELEMENT NAME

|1 | | |EI |R | | |01950 |Provider Product/Service Group Number

|2 | | |EI |O | | |01951 |Payer Product/Service Group Number

|3 |1..4 | |SI |R | | |01952 |Product/Service Group Sequence Number

|4 |1..1 | |ID |R | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70136[0136] |01953 |Adjudicate as Group

|5 | | |CP |R | | |01954 |Product/Service Group Billed Amount

|6 | |254# |ST |R | | |02044 |Product/Service Group Description

|===

=== PSG-1 Provider Product/Service Group Number (EI) 01950

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: Unique Product/Service Group Number assigned by the Provider Application.

=== PSG-2 Payer Product/Service Group Number (EI) 01951

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: Unique Product/Service Group Number assigned by the Payer Application

=== PSG-3 Product/Service Group Sequence Number (SI) 01952

=== PSG-4 Adjudicate as Group (ID) 01953

=== PSG-5 Product/Service Group Billed Amount (CP) 01954

Components: <Price (MO)> ^ <Price Type (ID)> ^ <From Value (NM)> ^ <To Value (NM)> ^ <Range Units (CWE)> ^ <Range Type (ID)>

Subcomponents for Price (MO): <Quantity (NM)> & <Denomination (ID)>

Subcomponents for Range Units (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Definition: Sum of all Product/Service Billed Amounts for all Product/Service Line Items for this Product/Service Group.

=== PSG-6 Product/Service Group Description (ST) 02044

