= PSS
:render_as: Level3
:v291_section: 16.4.4+

== PSS – Product/Service Section Segment

The Product/Service Section segment is used to form a logical grouping of Product/Service Group segments, Patients and Response Summaries for a particular Invoice.

HL7 Attribute Table – PSS – Product/Service Section

[width="100%",cols="14%,6%,7%,6%,6%,6%,7%,7%,41%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |R/O |RP/# |TBL# |ITEM# |ELEMENT NAME

|1 | | |EI |R | | |01946 |Provider Product/Service Section Number

|2 | | |EI |O | | |01947 |Payer Product/Service Section Number

|3 |1..4 | |SI |R | | |01948 |Product/Service Section Sequence Number

|4 | | |CP |R | | |01949 |Billed Amount

|5 | |254# |ST |R | | |02043 |Section Description or Heading

|===

=== PSS-1 Provider Product/Service Section Number (EI) 01946

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: Unique Product/Service Section Number assigned by the Provider Application.

=== PSS-2 Payer Product/Service Section Number (EI) 01947

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: Unique Product/Service Section Number assigned by the Payer Application.

=== PSS-3 Product/Service Section Sequence Number (SI) 01948

=== PSS-4 Billed Amount (CP) 01949

Components: <Price (MO)> ^ <Price Type (ID)> ^ <From Value (NM)> ^ <To Value (NM)> ^ <Range Units (CWE)> ^ <Range Type (ID)>

Subcomponents for Price (MO): <Quantity (NM)> & <Denomination (ID)>

Subcomponents for Range Units (CWE): <Identifier (ST)> & <Text (ST)> & <Name of Coding System (ID)> & <Alternate Identifier (ST)> & <Alternate Text (ST)> & <Name of Alternate Coding System (ID)> & <Coding System Version ID (ST)> & <Alternate Coding System Version ID (ST)> & <Original Text (ST)> & <Second Alternate Identifier (ST)> & <Second Alternate Text (ST)> & <Name of Second Alternate Coding System (ID)> & <Second Alternate Coding System Version ID (ST)> & <Coding System OID (ST)> & <Value Set OID (ST)> & <Value Set Version ID (DTM)> & <Alternate Coding System OID (ST)> & <Alternate Value Set OID (ST)> & <Alternate Value Set Version ID (DTM)> & <Second Alternate Coding System OID (ST)> & <Second Alternate Value Set OID (ST)> & <Second Alternate Value Set Version ID (DTM)>

Definition: Sum of all Product/Service Billed Amounts for all Product/Service Line Items for this Product/Service Section.

=== PSS-5 Section Description or Heading (ST) 02043

