= VND
:render_as: Level3
:v291_section: 17.5.4+

== VND – Purchasing Vendor Segment

This segment contains purchasing vendors that supply the inventory supply item specified in the ITM segment.

HL7 Attribute Table – VND – Purchasing Vendor

[width="100%",cols="14%,6%,7%,6%,6%,6%,7%,7%,41%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |OPT |RP/# |TBL# |ITEM# |ELEMENT NAME

|1 |1..4 | |SI |R | | |02217 |Set Id – VND

|2 | | |EI |R | | |02218 |Vendor Identifier

|3 | |999= |ST |O | | |02276 |Vendor Name

|4 | | |EI |O | | |02219 |Vendor Catalog Number

|5 | | |CNE |O | |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70532[0532] |02220 |Primary Vendor Indicator

|6 | | |EI |O |Y | |02420 |Corporation

|7 | | |XCN |O | | |02421 |Primary Contact

|8 | | |MOP |O | | |02422 |Contract Adjustment

|9 | | |EI |O |Y | |02423 |Associated Contract ID

|10 | | |ST |O |Y | |02424 |Class of Trade

|11 | | |CWE |O | | |02425 |Pricing Tier Level

|===

=== VND-1 Set ID - VND (SI) 02217

=== VND-2 Vendor Identifier (EI) 02218

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: This field contains the identifier of the vendor in the system.

=== VND-3 Vendor Name (ST) 02276

=== VND-4 Vendor Catalog Number (EI) 02219

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: This field contains the catalog number assigned to the item by a purchasing vendor.

=== VND-5 Primary Vendor Indicator (CNE) 02220

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: This field contains an indicator to communicate whether this purchasing vendor is the primary vendor used to place orders for inventory supply item. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70532[_HL7 Table 0532 - Expanded Yes/no Indicator_] in Chapter 2C, Code Tables, for valid values.

=== VND-6 Corporation (EI) 02420

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: This field contains a corporation indentifier (code and name) of the entity allowed to purchase from this contract for this vendor.

=== VND-7 Primary Contact (XCN) 02421

Components: <Person Identifier (ST)> ^ <Family Name (FN)> ^ <Given Name (ST)> ^ <Second and Further Given Names or Initials Thereof (ST)> ^ <Suffix (e.g., JR or III) (ST)> ^ <Prefix (e.g., DR) (ST)> ^ <WITHDRAWN Constituent> ^ <DEPRECATED-Source Table (CWE)> ^ <Assigning Authority (HD)> ^ <Name Type Code (ID)> ^ <Identifier Check Digit (ST)> ^ <Check Digit Scheme (ID)> ^ <Identifier Type Code (ID)> ^ <Assigning Facility (HD)> ^ <Name Representation Code (ID)> ^ <Name Context (CWE)> ^ <WITHDRAWN Constituent> ^ <Name Assembly Order (ID)> ^ <Effective Date (DTM)> ^ <Expiration Date (DTM)> ^ <Professional Suffix (ST)> ^ <Assigning Jurisdiction (CWE)> ^ <Assigning Agency or Department (CWE)> ^ <Security Check (ST)> ^ <Security Check Scheme (ID)>

Definition: This field contains the primary contact person of this vendor item.

=== VND-8 Contract Adjustment (MOP) 02422

Components: <Money or Percentage Indicator (ID)> ^ <Money or Percentage Quantity (NM)> ^ <Monetary Denomination (ID)>

Definition: This field contains the markup amount for this contract item and vendor combination.

=== VND-9 Associated Contract ID (EI) 02423

Components: <Entity Identifier (ST)> ^ <Namespace ID (IS)> ^ <Universal ID (ST)> ^ <Universal ID Type (ID)>

Definition: This field contains a contract that is linked to the contract sent in the CTR segment (described in Chapter 8). For example, the contract in CTR maybe of supplier type M (manufacturer); a contract sent in VND may be a linked distributor contract for a supplier authoized so distribute this item.

=== VND-10 Class of Trade (ST) 02424

=== VND-11 Pricing Tier Level (CWE) 02425

Components: <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^ <Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate Coding System (ID)> ^ <Coding System Version ID (ST)> ^ <Alternate Coding System Version ID (ST)> ^ <Original Text (ST)> ^ <Second Alternate Identifier (ST)> ^ <Second Alternate Text (ST)> ^ <Name of Second Alternate Coding System (ID)> ^ <Second Alternate Coding System Version ID (ST)> ^ <Coding System OID (ST)> ^ <Value Set OID (ST)> ^ <Value Set Version ID (DTM)> ^ <Alternate Coding System OID (ST)> ^ <Alternate Value Set OID (ST)> ^ <Alternate Value Set Version ID (DTM)> ^ <Second Alternate Coding System OID (ST)> ^ <Second Alternate Value Set OID (ST)> ^ <Second Alternate Value Set Version ID (DTM)>

Definition: This field contains the tier level at which this contract is priced for the vendor sent in this segment. Pricing Tier level determines the price of the item on the contract. Tier Level can be assigned to an IDN or at a corporation level and is typically based on volume purchased (determined by $ or a %). The larger the volume purchased, the lower priced tier level is assigned to the contract. This value can change over the life of the contract if purchasing volume changes after initial contract signing.Example 01^Tier One, 02^Tier 2, etc No HL7 table is defined here, because it needs to be defined by trading partner agreement, including the identification of code system to use.

