= Technical Specs
:render_as: Level4
:v291_section: 12.3.

Applications can have differing orientations for representing problem and goal hierarchies. For example, parent/child relationships may map problem(s) to goal(s), or goal(s) to problem(s). To accommodate these different orientations, the Problem message allows representation of goals that are functionally dependent upon a problem, and the Goal message allows representation of problems that are functionally dependent on a goal.

Due to the multiple occurrences of common segments such as Variance (VAR) and Notes (NTE), we have chosen to expand the segment definitions on the message diagrams to explicitly identify the hierarchical relationships. Examples of this would be "Variance (Goal)" and "Variance (Participation)." This does not imply unique segments, but indicates in the first case that the variance is related to its parent Goal, and in the second case that the variance is related to its parent Role.

The notation used to describe the sequence, the optionality, and the repetition of segments is described in Chapter 2, under "Format for defining abstract message."

Note: For all message definitions, the "OBR etc." notation represents all possible combinations of pharmacy and other order detail segments, as outlined in Chapter 4 conventions (See section 4.2.2.4, "Order detail segment").

xref:Technical_Specs/Message_-_PC6_Patient_Goal_Add.adoc[Message - PC6 Patient Goal Add]

xref:Technical_Specs/Message_-_PC7_Patient_Goal_Update.adoc[Message - PC7 Patient Goal Update]

xref:Technical_Specs/Message_-_PC8_Patient_Goal_Delete.adoc[Message - PC8 Patient Goal Delete]

xref:Technical_Specs/Message_-_PC1_Patient_Problem_Add.adoc[Message - PC1 Patient Problem Add]

xref:Technical_Specs/Message_-_PC2_Patient_Problem_Update.adoc[Message - PC2 Patient Problem Update]

xref:Technical_Specs/Message_-_PC3_Patient_Problem_Delete.adoc[Message - PC3 Patient Problem Delete]

xref:Technical_Specs/Message_-_PCB_Patient_Pathway_Add.adoc[Message - PCB Patient Pathway Add]

xref:Technical_Specs/Message_-_PCC_Patient_Pathway_Update.adoc[Message - PCC Patient Pathway Update]

xref:Technical_Specs/Message_-_PCD_Patient_Pathway_Delete.adoc[Message - PCD Patient Pathway Delete]

xref:Technical_Specs/Message_-_PCG_Patient_Pathway_Goal_Add.adoc[Message - PCG Patient Pathway Goal Add]

xref:Technical_Specs/Message_-_PCH_Patient_Pathway_Goal_Update.adoc[Message - PCH Patient Pathway Goal Update]

xref:Technical_Specs/Message_-_PCJ_Patient_Pathway_Goal_Delete.adoc[Message - PCJ Patient Pathway Goal Delete]

