= Message - M10 Master File Notification - Test/Observation Batteries
:render_as: Message Page
:v291_section: 8.8.1; 8.8.5

These segments define the format for the general information about the observations that a clinical or diagnostic service produces and sends to its "clients." This format can be used to send the producer's entire service/test/observation definition or a few of the producer's observations, such as those with procedure, technique, or interpretation changes.

In anticipation of an object-oriented organization of segments in future releases of this Standard, the attributes of observations/batteries have been grouped into seven different segments:

OM1 contains the attributes that apply to all observations

OM2 applies to numerically-valued observations

OM3 applies to text or code-valued observations

OM4 applies to observations or batteries that require specimens

OM5 contains the attributes of batteries, or sets of observations or other batteries

OM6 contains the quantities (observations in a most general sense) that are calculated from one or more other observations

OM7 contains additional basic attributes that apply to the definition of most observations/services.

Thus, the full definition of a numerically-valued laboratory observation would require the transmission of OM1, OM2, and OM4.

In the following discussion, we use OMx to refer to any of the seven observation-defining segments. Each instance of an OMx segment contains the information about one observation or observation battery. These OMx segments are designed to be "inclusive" and accommodate the attributes of many kinds of observations. Thus, the fact that a field is listed in a particular segment should not be construed as meaning that a producer must include information about that item in its definition transmission. Many fields will apply to some terms; others will not. One observation producer may choose to populate one set of fields; another may choose to populate a different set of fields, according to the requirements of that producer's "client."

Most of the fields of data type TX in those segments are intended to include information typically contained in a diagnostic service's user manual. Such fields should describe how the data is to be interpreted or used, and are not intended for computer interpretation.

Remember that the magnitude of a treatment can also be regarded as an observation and, as such, can be represented as an observation within these segments. Many examples exist. When a blood gas is transmitted, the requesting service usually transmits the amount of inspired O2 (a treatment) on requisition. (In an electronic transmission, the service would send this as an OBX segment, along with the electronic order for the test.) When blood levels are drawn, the amount and time of the last dose are routinely included as observations on the request for service. A pharmacy system could routinely send to a medical record system the average daily dose of each outpatient medication it dispenses. In such cases, the treatment amounts would be observations to the receiving system and would be transmitted as OBX segments. When received, they would be treated like any other observation. A medical record system could then create, for example, a flowchart of lab results, or lab results mixed with relevant treatments.

MFN^M10^MFN_M10: Master File Notification - Test/Observation Batteries

[width="100%",cols="33%,47%,9%,11%",options="header",]

|===

|Segments |Description |Status |Chapter

|MSH |Message Header | |2

|[\{ SFT }] |Software | |2

|[ UAC ] |User Authentication Credential | |2

|link:#MFI[MFI] |Master File Identification | |8

|\{ |--- MF_TEST_BATTERIES begin | |

|link:#MFE[MFE] |Master File Entry | |8

|link:#OM1[OM1] |General Segment (Fields That Apply to Most Observations) | |8

|[\{link:#OMC[OMC] }] |Supporting Clinical Information | |8

|[\{ PRT }] |Participation | |4

|[ |--- MF_TEST_BATT_DETAIL begin | |

|link:#OM5[OM5] |Observation Batteries | |8

|[\{ link:#OM4[OM4] }] |Observations that Require Specimens | |8

|] |--- MF_TEST_BATT_DETAIL end | |

|} |--- MF_TEST_BATTERIES end | |

|===

[width="100%",cols="17%,21%,4%,16%,21%,21%",options="header",]

|===

|Acknowledgement Choreography | | | | |

|MFN^M10^MFN_M10 | | | | |

|Field name |Field Value: Original mode |Field value: Enhanced mode | | |

|MSH-15 |Blank |NE |AL, SU, ER |NE |AL, SU, ER

|MSH-16 |Blank |NE |NE |AL, SU, ER |AL, SU, ER

|Immediate Ack |- |- |ACK^M10^ACK |- |ACK^M10^ACK

|Application Ack |MFK^M10^MFK_M01 |- |- |MFK^M10^MFK_M01 |MFK^M10^MFK_M01

|===

MFK^M10^MFK_M01: Master File Application Acknowledgment

[width="100%",cols="33%,47%,9%,11%",options="header",]

|===

|Segments |Description |Status |Chapter

|MSH |Message Header | |2

|[\{ SFT }] |Software | |2

|[ UAC ] |User Authentication Credential | |2

|MSA |Acknowledgment | |2

|[\{ ERR }] |Error | |2

|link:#MFI[MFI] |Master File Identification | |8

|[\{ link:#MFA[MFA] }] |Master File ACK segment | |8

|===

*Note:* The MFK message is used for an application acknowledgment in either the original or enhanced acknowledgment modes.

*Note:* _MFI-1 - Master File Identifier_ = OMC for observation batteries.

[width="100%",cols="23%,37%,10%,30%",options="header",]

|===

|Acknowledgement Choreography | | |

|MFK^M10^MFK_M01 | | |

|Field name |Field Value: Original mode |Field value: Enhanced mode |

|MSH-15 |Blank |NE |AL, SU, ER

|MSH-16 |Blank |NE |NE

|Immediate Ack |- |- |ACK^M10^ACK

|Application Ack |- |- |-

|===

[message-tabs, ["MFN^M10^MFN_M10", "MFN Interaction", "ACK^M10^ACK", "ACK Interaction", "MFK^M10^MFK_M01", "MFK Interaction"]]

