= Examples
:render_as: Level4
:v291_section: 17.10+

== Example Transactions

=== Inventory Item Master Catalog Add - Event M16

An inventory clerk in the General Supply Inventory location has added a new supply item to the item master catalog. A Master File Add message is sent (MAD) to notify selected inventory locations that this supply item has been added to the item master catalog

MSH|^~\&|MATERIALSYS|FACA|INVSYS|CENSUPPLY|200408150900||MFN^M16^MFN_M16|090849SUPITM|P|2.9|||AL|AL|||<cr>

MFI|INV|MATERIALSYS|UPD|200408121100|SU|<cr>

MFE|MAD|F589|200408121100|JMC090387^^JMFcr>

SFT|COMPAPP|9.0.0|MATIERALSYS|4500|200401010700|<cr>

UAC| KERB|MATSYS|AP|Octet-stream|A|Clerk|<cr>

ITM|10001|Formula 8oz|A|SUP|DietaryFormula|Y|ALR|MANUFACTURER|F589|ALR900||Y|300-0001^FormulaAlim_8oz|4.92|Y||FDA|N||100-9088-37887|20|29.75|N|N|N||||REF|<cr>

VND|001|M00933|VENDOR|FV9975|Y|<cr>

VND|002|M00934|VENDOR2|FV9976|N|<cr>

PKG|001|CS|6|Y|5|29.50|30.25|200409030100|<cr>

PKG|002|EA|N|1|4.92|5.04|200409030100|<cr>

PCE|001|9188|300-0002|5.35|<cr>

ITV|001|GS^General Stores|CS^Central Supply|1|GS-031|CS|EA|100-9200-00000|Y|300-0001|4.95||Y|N|N||||M|30|450|100|400|N|<cr>

MSH|^~\&|MATERIALSYS|FACA|INVSYS|CENSUPPLY|200408150900||MFN^M16^MFN_M16|090849SUPITM|P|2.9|||AL|AL|||<cr>

MSA|CA|8000|||||<cr>

=== Request New Sterilization Lot - Event S28

The sterilizer operator is preparing to run a flash sterilizer load. The sterilizer requests a lot number from the instrument-tracking system to assign to the load.

MSH|^~\&|Sterila|FacilB|Instrutrak|FacilA|200410010800||SLR^S28 SLR_S28|021244STER|P|2.9|||AL|AL||||||<cr>

SFT|Hospital A|9.0|Sterila|10101010|9.0 999|New Load|200402140900|<cr>

UAC|KERB|MATSYS|AP|Octet-stream|A|Clerk|<cr>

SLT|87995|DEVICE NAME|A46|LF4|1435567677<cr>

MSH|^~\&|Sterila|FacilB|Instrutrak|FacilA|200410010800||ACK^S28^ACK|021244STER|P|2.9|||NE|NE||||||<cr>

MSA|CA|021244STER||||<cr>

MSH|^~\&|Instrutrak|FacilB|Sterila|FacilA|2004010010801||SLS^S28 SLR_S28|021244STER|P|2.9|||AL|NE|||||<cr>

SFT|Hospital A|9.0|Sterila|10101010|9.0 999|New Load|200402140900|<cr>

UAC|KERB|MATSYS|AP|Octet-stream|A|Admin|<cr>

SLT|01||||<cr>

MSH|^~\&|Instrutrak|FacilB|Sterila|FacilA|2004010010801||SLS^S28|021244STER|P|2.9|||NE|NE||||||<cr>

MSA|CA|021244STER||||<cr>

