= Technical Specs
:render_as: Level4
:v291_section: 17.6; 17.7

Placer request and filler response transactions are the messages and trigger events used between placer applications and filler applications. The placer application initiates transactions using the *SLR, STI, SDR,* or *SMD* message types, requesting information with the given trigger event message detail. The filler application responds to these requests, using the *SLS, STS, SDS,* or *SMS* message types, to either grant or deny the requests from the placer application.

When initiating a request, the placer application will generate and send a message type containing all of the information necessary to communicate the desired action to the filler application. All required segments and fields (both explicitly required and conditionally required) should be provided to the filler application, as defined in this chapter. When the filler application receives the transaction, it acknowledges it with the appropriate accept acknowledgment using an *ACK* message (assuming that the enhanced acknowledgment mode is in use).

After processing the request at the application level, the filler acknowledges the transaction with the appropriate application acknowledgment in a response message type (again assuming that an application acknowledgment was requested under the enhanced acknowledgment mode or that the original acknowledgment mode is in use). Applying the explanations of the various application acknowledgment codes in the context of this chapter, an application accept from the filler means that the request was processed and accepted by the filler.

An application error from the filler means that the request was processed and denied. An application reject from the filler means that the request was not, and could not be, processed due to one or more reasons unrelated to its content (for example, it fails the basic application protocol validation, the filler system is down, or there was an internal error).

There are no unsolicited messages initiated from a filler application defined in this set of trigger events. Those messages and trigger events are defined below, in section _17.7_, "_Filler Application Messages and Trigger Events Unsolicited_."

All of the trigger events associated with placer request and filler response transactions use the message definitions that follow:

Unsolicited transactions from filler applications are the messages and trigger events used between filler applications and auxiliary applications. Transactions are initiated by the filler application, using the *STC* message to notify auxiliary applications of a sterilization configuration set. The auxiliary application responds to these notifications, using the *ACK* message, either to acknowledge receipt of the transaction, or to signal that an interfacing error of some kind has occurred.

As the discussion of application roles has indicated above, any one application can have more than one application role. If it is important that the application acting in the placer application role in your messaging environment be notified of unsolicited sterilization configurations, then it must also support the role of an auxiliary application.

When initiating a notification transaction, the filler application will generate and send an *STC, SLN, SDN,* or *SCN* message containing all of the information necessary to communicate the desired information to the auxiliary application. All required segments and fields (both explicitly required and conditionally required) should be provided by the filler application, as defined in this chapter. When the auxiliary application receives the transaction, it acknowledges with the appropriate accept acknowledgment using an *ACK* message (assuming that the enhanced acknowledgment mode is in use). After processing the notification at the application level, the auxiliary application acknowledges the transaction with the appropriate application acknowledgment in an *ACK* message (assuming that an application acknowledgment was requested under the enhanced acknowledgment mode or that the original acknowledgment mode is in use). Applying the explanations of the various application acknowledgment codes (detailed in Chapter 2) in the context of this chapter, an application accept from the auxiliary application means that the notification was processed and accepted. An application error from the auxiliary application means that the auxiliary application was unable to process the notification at the application level. An application reject from the auxiliary application means that the request was not, and could not be, processed due to one or more reasons unrelated to its content (for example, it fails the basic application protocol validation, the system is down, or there was an internal error).

xref:Technical_Specs/Message_-_S28_Request_New_Sterilization_Lot.adoc[Message - S28 Request New Sterilization Lot]

xref:Technical_Specs/Message_-_S29_Request_Sterilization_Lot_Deletion.adoc[Message - S29 Request Sterilization Lot Deletion]

xref:Technical_Specs/Message_-_S30_Request_Item.adoc[Message - S30 Request Item]

xref:Technical_Specs/Message_-_S31_Request_Anti-Microbial_Device_Data.adoc[Message - S31 Request Anti-Microbial Device Data]

xref:Technical_Specs/Message_-_S32_Request_Anti-Microbial_Device_Cycle_Data.adoc[Message - S32 Request Anti-Microbial Device Cycle Data ]

xref:Technical_Specs/Message_-_S33_Notification_of_Sterilization_Configuration.adoc[Message - S33 Notification of Sterilization Configuration]

xref:Technical_Specs/Message_-_S34_Notification_of_New_Sterilization_Lot.adoc[Message - S34 Notification of New Sterilization Lot]

xref:Technical_Specs/Message_-_S35_Notification_of_Sterilization_Lot_Deletion.adoc[Message - S35 Notification of Sterilization Lot Deletion]

xref:Technical_Specs/Message_-_S36_Notification_of_Anti-Microbial_Device_Data.adoc[Message - S36 Notification of Anti-Microbial Device Data ]

xref:Technical_Specs/Message_-_S37_Notification_of_Anti-Microbial_Device_Cycle_Data.adoc[Message - S37 Notification of Anti-Microbial Device Cycle Data]

