= CD
:render_as: Level3
:v291_section: 2A.2.5+

== CD - channel definition

*Attention: _Retained for backward compatibility onlyas of v 2.7_.* This is used only in the waveform message, CHM category, which has been retained for backward compatibility only in v 2.7.

HL7 Component Table - CD – Channel Definition

[width="99%",cols="10%,7%,8%,6%,7%,7%,32%,13%,10%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |OPT |TBL# |COMPONENT NAME |COMMENTS |SEC.REF.

|1 | | |WVI |O | |Channel Identifier | |2A.2.85

|2 | | |WVS |O | |Waveform Source | |2A.2.86

|3 | | |CSU |O | |Channel Sensitivity and Units | |2A.2.12

|4 | | |CCP |O | |Channel Calibration Parameters | |2A.2.4

|5 | |6# |NM |O | |Channel Sampling Frequency | |2A.2.47

|6 | | |NR |O | |Minimum and Maximum Data Values | |2A.2.48

|===

Definition: This data type is used for labeling of digital waveform data. It defines a recording channel, which is associated with one of the values in each time sample of waveform data. Each channel has a number (which generally defines its position in a multichannel display) and an optional name or label (also used in displays). One or two named waveform sources may also be associated with a channel (providing for the use of differential amplifiers with two inputs). The other components of the channel definition data type are optional. The individual components are defined as follows:

=== Channel Identifier (WVI)

=== Waveform Source (WVS)

=== Channel Sensitivity and Units (CSU)

=== Channel Calibration Parameters (CCP)

=== Channel Sampling Frequency (NM)

=== Minimum and Maximum Data Values (NR)

*Note:* this is the frequency of transmitted data, which may or may not be the actual frequency at which the data was acquired by an analog-to-digital converter or other digital data source (i.e. the data transmitted may be subsampled, or interpolated, from the originally acquired data.)

Definition: This component defines the minimum and maximum data values which can occur in this channel in the digital waveform data, that is, the range of the ADC. , and also specifies whether or not non-integral data values may occur in this channel in the waveform data. If the minimum and maximum values are both integers (or not present), only integral data values may be used in this channel. If either the minimum or the maximum value contains a decimal point, then non-integral as well as integral data values may be used in this channel. For an n-bit signed ADC, the nominal baseline B = 0, and the minimum (L) and maximum (H) values may be calculated as follows:

____

L = -2n^-1^

H = 2n^-1^ - 1

____

For an unsigned n-bit ADC, the minimum value L = 0, and the nominal baseline value (B) and maximum value (H) may be calculated from the formulas,

____

B = 2n^-1^

H = 2n - 1

____

The actual signal amplitude A (for differentially amplified potential measurements, the potential at electrode number one minus that at electrode number two) may be calculated from the value D (range L to H) in the waveform data using the actual baseline value B and the nominal sensitivity S and actual sensitivity correction factor C by the formula,

____

_A = SC(D-B)_

____

