= CF
:render_as: Level3
:v291_section: 2A.2.7+

== CF - coded element with formatted values

As of v2.7 a third tuple, formerly known as triplet, has been added to the CF data type. Additionally, 3 new components were added to each tuple such that each tuple now has a total of 7 components. The Original Text component applies to the CF as a whole.

HL7 Component Table - CF – Coded Element with Formatted Values

[width="99%",cols="10%,7%,8%,6%,7%,7%,32%,13%,10%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |OPT |TBL# |COMPONENT NAME |COMMENTS |SEC.REF.

|1 | |20= |ST |O | |Identifier | |2A.2.76

|2 | | |FT |O | |Formatted Text | |2A.2.31

|3 |1..12 | |ID |C |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[0396] |Name of Coding System | |2A.2.35

|4 | |20= |ST |O | |Alternate Identifier | |2A.2.76

|5 | | |FT |O | |Alternate Formatted Text | |2A.2.31

|6 |1..12 | |ID |C |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[0396] |Name of Alternate Coding System | |2A.2.35

|7 | |10= |ST |C | |Coding System Version ID | |2A.2.76

|8 | |10= |ST |O | |Alternate Coding System Version ID | |2A.2.76

|9 | |199# |ST |O | |Original Text | |2A.2.76

|10 | |20= |ST |O | |Second Alternate Identifier | |2A.2.76

|11 | | |FT |O | |Second Alternate Formatted Text | |2A.2.76

|12 |1..12 | |ID |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[0396] |Name of Second Alternate Coding System | |2A.2.35

|13 | |10= |ST |C | |Second Alternate Coding System Version ID | |2A.2.76

|14 | |199= |ST |C | |Coding System OID | |2A.2.76

|15 | |199= |ST |O | |Value Set OID | |2A.2.76

|16 | |8= |DTM |C | |Value Set Version ID | |2A.2.76

|17 | |199= |ST |C | |Alternate Coding System OID | |2A.2.76

|18 | |199= |ST |O | |Alternate Value Set OID | |2A.2.76

|19 | |8= |DTM |C | |Alternate Value Set Version ID | |2A.2.76

|20 | |199= |ST |C | |Second Alternate Coding System OID | |2A.2.76

|21 | |199= |ST |O | |Second Alternate Value Set OID | |2A.2.76

|22 | |8= |DTM |C | |Second Alternate Value Set Version ID | |2A.2.76

|===

*Note:* The Vocabulary TC is the steward of the CF data type.

Definition: This data type transmits codes and the formatted text associated with the code. This data type can be used to transmit for the first time the formatted text for the *canned text* portion of a report, for example, a standard radiological description for a normal chest X‑ray. The receiving system can store this information and in subsequent messages only the identifier need be sent. Another potential use of this data type is transmitting master file records that contain formatted text. This data type has six components as follows:

The components, primary and alternate, are defined exactly as in the CE data type with the exception of the second and fifth components, which are of the formatted text data type.

Example:

OBX||CF|71020^CXR^99CPMC||79989^\H\Description:\N\\.sp\\ti+4\Heart is not enlarged. There is no evidence of pneumonia, effusion, pneumothorax or any masses. \.sp+3\\H\Impression:\N\\.sp\\.ti+4\Negative chest.^99CPMC

=== Identifier (ST)

=== Second Alternate Identifier (ST)

=== Second Alternate Formatted Text (FT)

=== Name of Second Alternate Coding System (ID)

Definition: Identifies the coding scheme being used in the Second Alternate Identifier component. Analogous to _CF. Name of Coding System_.

This component is required when _CF.10_ is populated and _CF.20_ is not populated. Both _CF.10_ and _CF.20_ may be populated. Receivers should not identify a code based on its position within the tuples (Identifier, Alternate Identifier, or Second Alternate Identifier) or position within a repeating field. Instead, the receiver should always examine the coding ystem as specified in _CF.12_ and/or _CF.20_ the Coding System component or the Coding System OID for the tuple.

=== Second Alternate Coding System Version ID (ST)

=== Coding System OID (ST)

Definition: This component contains the ISO Object Identifier (OID) for the coding system or value set named in CNE.3. The value for this component is 2.16.840.1.113883.12.#### where "####" is to be replaced by the HL7 table number in the case of an HL7 defined or user defined table. For externally defined code systems the OID registered in the HL7 OID registry SHALL be used.

This component is required when _CF.1_ is populated and _CF.3_ is not populated. Both _CF.3_ and _CF.14_ may be populated.

=== Value Set OID (ST)

=== Value Set Version ID (DTM)

Definition: This component carries the version for the value set identified by _CF.15_. The version is a date. The date is the date/time that the value set being used was published.

Value set version ID is required if _CF.15_ is populated.

*Note*: If a code is provided, the meaning of the code must come from the definition of the code in the code system. The meaning of the code SHALL NOT depend on the value set. Applications SHALL NOT be required to interpret the code in light of the valueSet, and they SHALL NOT reject an instance because of the presence or absence of any or a particular value set/ value set version ID.

=== Alternate Coding System OID (ST)

Definition: This component contains the ISO Object Identifier (OID) for the coding system or value set named in _CF.6_. Analogous To _CF.14 Coding System OID_.

The value for this component is 2.16.840.1.113883.12.#### where "####" is to be replaced by the HL7 table number in the case of an HL7 defined or user defined table. For externally defined code systems the OID registered in the HL7 OID registry SHALL be used.

This component is required when _CF.4_ is populated and _CF.6_ is not populated. Both _CF.6_ and _CF.17_ may be populated.

=== Alternate Value Set OID (ST)

Definition: This component contains the ISO Object Identifier (OID) to allow identification of the value set from which the value in _CF.4_ is obtained. The value for this component is 2.16.840.1.113883.12.#### where "####" is to be replaced by the HL7 table number in the case of an HL7 defined or user defined table. For externally defined value sets, the OID registered in the HL7 OID registry SHALL be used.

*Note*: If a code is provided, the meaning of the code must come from the definition of the code in the code system. The meaning of the code SHALL NOT depend on the value set. Applications SHALL NOT be required to interpret the code in light of the valueSet, and they SHALL NOT reject an instance because of the presence or absence of any or a particular value set/ value set version ID.

A value set may or need not be present irrespective of other fields.

=== Alternate Value Set Version ID (DTM)

Definition: This component carries the version for the value set identified by _CF.18_. The version is a date. The date is the date/time that the value set being used was published.

Value set version ID is required if _CF.18_ is populated.

=== Formatted Text (FT)

=== Second Alternate Coding System OID (ST)

Definition: This component contains the ISO Object Identifier (OID) for the coding system or value set named in _CF.12_. Analogous To _CF.14 Coding System OID_.

The value for this component is 2.16.840.1.113883.12.#### where "####" is to be replaced by the HL7 table number in the case of an HL7 defined or user defined table. For externally defined code systems the OID registered in the HL7 OID registry SHALL be used.

This component is required when _CF.10_ is populated and _CF.12_ is not populated. Both _CF.12_ and _CF.20_ may be populated.

=== Second Alternate Value Set OID (ST)

Definition: This component contains the ISO Object Identifier (OID) to allow identification of the value set from which the value in _CF.10_ is obtained. The value for this component is 2.16.840.1.113883.12.#### where "####" is to be replaced by the HL7 table number in the case of an HL7 defined or user defined table. For externally defined value sets, the OID registered in the HL7 OID registry SHALL be used.

*Note*: If a code is provided, the meaning of the code must come from the definition of the code in the code system. The meaning of the code SHALL NOT depend on the value set. Applications SHALL NOT be required to interpret the code in light of the valueSet, and they SHALL NOT reject an instance because of the presence or absence of any or a particular value set/ value set version ID.

A value set may or need not be present irrespective of other fields.

=== Second Alternate Value Set Version ID (DTM)

Definition: This component carries the version for the value set identified by _CF.21_. The version is a date. The date is the date/time that the value set being used was published.

Value set version ID is required if _CF.21_ is populated.

=== Name of Coding System (ID)

Definition: Contains the name of the coding system employed.

Refer to E:\\V2\\v2.9 final Nov from Frank\\V29_CH02C_Tables.docx#HL70396[HL7 Table 0396 - Coding System] in Chapter 2C, Code Tables, for valid values.

As of v2.7 this component is required when _CF.1_ is populated and _CF.14_ is not populated. Both _CF.3_ and _CF.14_ may be populated. Receivers should not identify a code based on its position within the tuples (Identifier, Alternate Identifier, or Second Alternate Identifier) or position within a repeating field. Instead, the receiver should always examine the coding system as specified in _CF.3_ and/or _CF.14_, the Coding System component or the Coding System OID, for the tuple.

=== Alternate Identifier (ST)

Definition: A sequence of characters that uniquely identifies an alternate code. Analogous to _CF-1 Identifier_.

*Usage Notes:* The Alternate Identifier is used to represent the local or user seen code as described. If present, it obeys the same rules of use and interpretation as described for component 1. If both are present, the identifiers in component 4 and component 1 should have exactly the same meaning, i.e., they should be exact synonyms.

=== Alternate Formatted Text (FT)

=== Name of Alternate Coding System (ID)

Definition: Contains the name of the coding system employed for the alternate identifier. Analogous to _CF.3 Name of Coding System_.

Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[HL7 Table 0396 - Coding System] in Chapter 2C, Code Tables, for valid values.

As of v2.7 this component is required when _CF.4_ is populated and _CF.17_ is not populated. Both _CF.6_ and _CF.17_ may be populated. Receivers should not identify a code based on its position within the tuples (Identifier, Alternate Identifier, or Second Alternate Identifier) or position within a repeating field. Instead, the receiver should always examine the coding ystem as specified in _CF.6_ and/or _CF.17_, the Coding System component or the Coding System OID, for the tuple.

=== Coding System Version ID (ST)

=== Alternate Coding System Version ID (ST)

=== Original Text (ST)

