= CNE
:render_as: Level3
:v291_section: 2A.2.8+

== CNE – coded with no exceptions

As of v2.7 a third tuple, formerly known as triplet, has been added to the CNE data type. Additionally, 3 new components were added to each tuple such that each tuple now has a total of 7 components. The Original Text component applies to the CNE as a whole.

HL7 Component Table - CNE – Coded with No Exceptions

[width="99%",cols="10%,7%,8%,6%,7%,7%,32%,13%,10%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |OPT |TBL# |COMPONENT NAME |COMMENTS |SEC.REF.

|1 | |20= |ST |R | |Identifier | |2A.2.76

|2 | |199# |ST |O | |Text | |2A.2.76

|3 |1..12 | |ID |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[0396] |Name of Coding System | |2A.2.35

|4 | |20= |ST |O | |Alternate Identifier | |2A.2.76

|5 | |199# |ST |O | |Alternate Text | |2A.2.76

|6 |1..12 | |ID |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[0396] |Name of Alternate Coding System | |2A.2.35

|7 | |10= |ST |C | |Coding System Version ID | |2A.2.76

|8 | |10= |ST |O | |Alternate Coding System Version ID | |2A.2.76

|9 | |199# |ST |O | |Original Text | |2A.2.76

|10 | |20= |ST |O | |Second Alternate Identifier | |2A.2.76

|11 | |199# |ST |O | |Second Alternate Text | |2A.2.76

|12 |1..12 | |ID |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[0396] |Name of Second Alternate Coding System | |2A.2.35

|13 | |10= |ST |C | |Second Alternate Coding System Version ID | |2A.2.76

|14 | |199= |ST |C | |Coding System OID | |2A.2.76

|15 | |199= |ST |O | |Value Set OID | |2A.2.76

|16 | |8= |DTM |C | |Value Set Version ID | |2A.2.22

|17 | |199= |ST |C | |Alternate Coding System OID | |2A.2.76

|18 | |199= |ST |O | |Alternate Value Set OID | |2A.2.76

|19 | |8= |DTM |C | |Alternate Value Set Version ID | |2A.2.22

|20 | |199= |ST |C | |Second Alternate Coding System OID | |2A.2.76

|21 | |199= |ST |O | |Second Alternate Value Set OID | |2A.2.76

|22 | |8= |DTM |C | |Second Alternate Value Set Version ID | |2A.2.22

|===

*Note:* The Vocabulary TC is the steward of the CNE data type.

Definition: Specifies a coded element and its associated detail. The CNE data type is used when a required or mandatory coded field is needed. The specified HL7 table or imported or externally defined coding system must be used and may not be extended with local values. Text may not replace the code. A CNE field must have an HL7 defined or external table associated with it. A CNE field may be context sensitive such that a choice of explicit coding systems might be designated. This allows for realm and other types of specificity. Every effort will be made to enumerate the valid coding system(s) to be specified in the 3rd component, however, the standards body realizes that this is impossible to fully enumerate.

*Note*: The presence of two sets of equivalent codes in this data type is semantically different from a repetition of a CNE-type field. With repetition, several distinct codes (with distinct meanings) may be transmitted.

Example 1: The drug must be coded and must be taken from the specified coding system. The coding system is an external coding system. Example is derived from _FT1-26_.

|0006-0106-58^Prinivil 10mg oral tablet^NDC|

Example 2: Consent mode must be coded and must be taken from the specified coding system. The coding system is an HL7 code table. Example is taken from _CON-10_.

|V^Verbal^HL70497^^^^2.8|

=== Identifier (ST)

Definition: The first component contains the sequence of characters (the code) that uniquely identifies the item being referenced by the _CNE.2_. Different coding schemes will have different elements here.

*Usage Note*: The identifier is required and must be a valid code.

=== Second Alternate Identifier (ST)

=== Second Alternate Text (ST)

=== Name of Second Alternate Coding System (ID)

Definition: Identifies the coding scheme being used in the Second Alternate Identifier component. Analogous to _CNE.3 Name of Coding System_. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[HL7 Table 0396 - Coding Systems] in Chapter 2C, Code Tables, for valid values.

As of v2.7 this component is required when _CNE.10_ is populated and _CNE.20_ is not populated. Both _CNE.12_ and _CNE.20_ may be populated. Receivers should not identify a code based on its position within the tuples (Identifier, Alternate Identifier, or Second Alternate Identifier) or position within a repeating field. Instead, the receiver should always examine the codingSystem as specified in _CNE.12_ and/or _CNE.20_, the "Coding System" component or the "Coding System OID", for the tuple.

=== Second Alternate Coding System Version ID (ST)

=== Coding System OID (ST)

Definition: This component contains the ISO Object Identifier (OID) for the coding system or value set named in _CNE.3_. The value for this component is 2.16.840.1.113883.12.#### where "####" is to be replaced by the HL7 table number in the case of an HL7 defined or user defined table. For externally defined code systems the OID registered in the HL7 OID registry SHALL be used.

This component is required when _CNE.1_ is populated and _CNE.3_ is not populated. Both _CNE.3_ and _CNE.14_ may be populated.

=== Value Set OID (ST)

Definition: This component contains the ISO Object Identifier (OID) to allow identification of the value set from which the value in _CNE.1_ is obtained. The value for this component is 2.16.840.1.113883.12.#### where "####" is to be replaced by the HL7 table number in the case of an HL7 defined or user defined table. For externally defined value sets, the OID registered in the HL7 OID registry SHALL be used.

A value set may or need not be present irrespective of other fields.

*Note*: If a code is provided, the meaning of the code must come from the definition of the code in the code system. The meaning of the code SHALL NOT depend on the value set. Applications SHALL NOT be required to interpret the code in light of the valueSet, and they SHALL NOT reject an instance because of the presence or absence of any or a particular value set/ value set version ID.

=== Value Set Version ID (DTM)

Definition: This component carries the version for the value set identified by _CNE.15_. The version is a date. The date is the date/time that the value set being used was published.

Value set version ID is required if _CNE.15_ is populated.

=== Alternate Coding System OID (ST)

Definition: This component contains the ISO Object Identifier (OID) for the coding system or value set named in _CNE.6_. Analogous to _CNE.14 OID for Coding System_.

The value for this component is 2.16.840.1.113883.12.#### where "####" is to be replaced by the HL7 table number in the case of an HL7 defined or user defined table. For externally defined code systems the OID registered in the HL7 OID registry SHALL be used.

This component is required when _CNE.4_ is populated and _CNE.6_ is not populated. Both _CNE.6_ and _CNE.17_ may be populated.

=== Alternate Value Set OID (ST)

Definition: This component contains the ISO Object Identifier (OID) to allow identification of the value set from which the value in _CNE.4_ is obtained. The value for this component is 2.16.840.1.113883.12.#### where "####" is to be replaced by the HL7 table number in the case of an HL7 defined or user defined table. For externally defined value sets, the OID registered in the HL7 OID registry SHALL be used.

*Note*: If a code is provided, the meaning of the code must come from the definition of the code in the code system. The meaning of the code SHALL NOT depend on the value set. Applications SHALL NOT be required to interpret the code in light of the valueSet, and they SHALL NOT reject an instance because of the presence or absence of any or a particular value set/ value set version ID.

A value set may or need not be present irrespective of other fields.

=== Alternate Value Set Version ID (DTM)

Definition: This component carries the version for the value set identified by _CNE.18_. The version is a date. The date is the date/time that the value set being used was published.

Value set version ID is required if _CNE.18_ is populated.

=== Text (ST)

Definition: The second component contains the descriptive or textual name of the identifier, e.g., myocardial infarction or X-ray impression. This is the corresponding text assigned by the coding system to the identifier.

*Usage Note*: Text description of code is optional but its use should be encouraged since it makes messages easier to review for accuracy, especially during interface testing and debugging.

=== Second Alternate Coding System OID (ST)

Definition: This component contains the ISO Object Identifier (OID) from which the value in _CNE.12_ is obtained. The value for this component is 2.16.840.1.113883.12.#### where "####" is to be replaced by the HL7 table number in the case of an HL7 defined or user defined table. For externally defined numbers, the OID registered in the HL7 OID registry should be used.

This component is required when _CNE.4_ is populated and neither _CNE.6_ nor _CNE.18_ is populated. In short either the _CNE.6_ or the _CNE.14_ or _CNE.17_ must be populated when _CNE.4_ is populated.

=== Second Alternate Value Set OID (ST)

Definition: This component contains the ISO Object Identifier (OID) to allow identification of the value set from which the value in _CNE.10_ is obtained. The value for this component is 2.16.840.1.113883.12.#### where "####" is to be replaced by the HL7 table number in the case of an HL7 defined or user defined table. For externally defined value sets, the OID registered in the HL7 OID registry SHALL be used. A value set may or need not be present irrespective of other fields.

*Note*: If a code is provided, the meaning of the code must come from the definition of the code in the code system. The meaning of the code SHALL NOT depend on the value set. Applications SHALL NOT be required to interpret the code in light of the valueSet, and they SHALL NOT reject an instance because of the presence or absence of any or a particular value set/ value set version ID.

=== Second Alternate Value Set Version ID (DTM)

Definition: This component carries the version for the value set identified by _CNE.21_. The version is a date. The date is the date/time that the value set being used was published.

Value set version ID is required if _CNE.21_ is populated.

=== Name of Coding System (ID)

Definition: The third component contains the code for the name of the coding system from which the value in _CNE.1_ is obtained. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[HL7 Table 0396 - Coding Systems] in Chapter 2C, Code Tables, for valid values. Each coding system is assigned a unique identifier.

As of v2.7 this component is required when _CNE.1_ is populated and _CNE.14_ is not populated. Both _CNE.3_ and _CNE.14_ may be populated. Receivers should not identify a code based on its position within the tuples (Identifier, Alternate Identifier, or Second Alternate Identifier) or position within a repeating field. Instead, the receiver should always examine the codingSystem as specified in _CNE.3_ and/or _CNE.14_ the Coding System component or the Coding System OID for the tuple.The combination of the *identifier* and *name of coding system* represent a unique concept for a data item.

Some organizations that publish code sets author more than one. The coding system, then, to be unique, is a concatenation of the name of the coding authority organization and the name of its code set or table. When an HL7 table is used for a CNE data type, the *_name of coding system_* component is defined as *_HL7nnnn_* where *_nnnn_* is the HL7 table number. Similarly, ISO tables will be named ISOnnnn, where nnnn is the ISO table number.

*Usage Note: The following statement is retained for backward compatibility as of v2.7.* Best practice would recommend that this component always be populated. However, if the field narrative explicitly states "_Refer to HL7 Table nnnn for valid values_”, and, if the sending and receiving systems are HL7 compliant, the coding system would be known from the standard. This would be similar to a field with an ID data type, except that there is a second triplet in which to express an alternate code.

=== Alternate Identifier (ST)

Definition: A sequence of characters that uniquely identifies an alternate code. Analogous to _CNE.1_ _Identifier_.

*Usage Notes:* The Alternate Identifier is used to represent the local or user seen code as described. If present, it obeys the same rules of use and interpretation as described for component 1. If both are present, the identifiers in component 4 and component 1 should have exactly the same meaning, i.e., they should be exact synonyms.

=== Alternate Text (ST)

Definition: The descriptive or textual name of the alternate identifier. Analogous to _CNE.2 Text_.

*Usage Notes:* If present, _CNE.5_ obeys the same rules of use and interpretation as described for _CNE.2_.

=== Name of Alternate Coding System (ID)

Definition: Identifies the coding scheme being used in the alternate identifier component. Analogous to _CNE.3 Name of Coding System_. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[HL7 Table 0396 - Coding Systems] in Chapter 2C, Code Tables, for valid values.

As of v2.7 this component is required when _CNE.4_ is populated and _CNE.17_ is not populated. Both _CNE.6_ and _CNE.17_ may be populated. Receivers should not identify a code based on its position within the tuples (Identifier, Alternate Identifier, or Second Alternate Identifier) or position within a repeating field. Instead, the receiver should always examine the codingSystem as specified in _CNE.6_ and/or _CNE.17_, the "Coding System" component or the "Coding System OID", for the tuple.

*Usage Notes:* If present, _CNE.6_ obeys the same rules of use and interpretation as described for _CNE.3_.

=== Coding System Version ID (ST)

Definition: the version ID for the coding system identified by _CNE.3_. It belongs conceptually to components 1-3 and appears here only for reasons of backward compatibility.

*Usage Note:* If the coding system is any system other than an "HL7 coding system," version ID must be valued with an actual version ID. If the coding system is "HL7 coding system," version ID may have an actual value or it may be absent. If version ID is absent, it will be interpreted to have the same value as the HL7 version number in the message header. Text description of code is optional but its use should be encouraged since it makes messages easier to review for accuracy, especially during interface testing and debugging.

=== Alternate Coding System Version ID (ST)

Definition: the version ID for the coding system identified by _CNE.6_. It belongs conceptually to the group of Alternate components (see note _2A.2.1_) and appears here only for reasons of backward compatibility. Analogous to _CNE.7 Coding System Version ID_.

*Usage Notes:* If present, _CNE.8_ obeys the same rules of use and interpretation as described for _CNE.7_.

=== Original Text (ST)

