= CNN
:render_as: Level3
:v291_section: 2A.2.9+

== CNN - composite ID number and name simplified

*Attention: _Retained for backward compatibility only in version 2.6. Fields associated with this data type have been replaced by the ROL segment._*

HL7 Component Table - CNN - Composite ID Number and Name Simplified

[width="99%",cols="10%,7%,8%,6%,7%,7%,32%,13%,10%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |OPT |TBL# |COMPONENT NAME |COMMENTS |SEC.REF.

|1 | |15= |ST |O | |ID Number | |2A.2.76

|2 | |50# |ST |O | |Family Name | |2A.2.76

|3 | |30# |ST |O | |Given Name | |2A.2.76

|4 | |30# |ST |O | |Second and Further Given Names or Initials Thereof | |2A.2.76

|5 | |20# |ST |O | |Suffix (e.g., JR or III) | |2A.2.76

|6 | |20# |ST |O | |Prefix (e.g., DR) | |2A.2.76

|7 | |6= |IS |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70360[0360] |Degree (e.g., MD) | |2A.2.36

|8 | |4= |IS |C |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70297[0297] |Source Table | |2A.2.36

|9 | |20= |IS |C |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70363[0363] |Assigning Authority - Namespace ID | |2A.2.36

|10 | |199= |ST |C | |Assigning Authority - Universal ID | |2A.2.76

|11 |1..6 | |ID |C |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70301[0301] |Assigning Authority - Universal ID Type | |2A.2.35

|===

Definition: Specifies a person using both an identifier and the person’s name. Retained for backward compatibility only as of v2.6.

*Note:* Restores the original data type CN as was initially implementable in the CM used in sections 4.5.3.32 and 7.4.1.32 - (OBR-32), 4.5.3.33 and 7.4.1.33 - ( OBR-33), 4.5.3.34 and 7.4.1.34 - ( OBR-34), 4.5.3.35 and 7.4.1.35 - (OBR-35). Components 7 and 8, however, have been promoted to data type IS to be consistent with current practice without violating backward compatibility.

=== ID Number (ST)

=== Assigning Authority - Universal ID (ST)

See section, _2A.2.14.4_, "_Assigning Authority (HD)_" for definition.

If _CNN.11_ is valued, this component must be valued. If component 1 is valued, either _CNN.8_ or _CNN.9_, or both _CNN.10_ and _CNN.11_, must be valued.

=== Assigning Authority - Universal ID Type (ID)

See section, _2A.2.14.4_, "_Assigning Authority (HD)_" for definition. If this component is a known UID refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70301[_HL7 Table 0301 - Universal ID type_] in Chapter 2C, Code Tables, for valid values.

If _CNN.10_ is valued, this component must be valued. If component 1 is valued, either _CNN.8_ or _CNN.9_, or both _CNN.10_ and _CNN.11_, must be valued.

=== Family Name (ST)

=== Given Name (ST)

=== Second and Further Given Names or Initials Thereof (ST)

=== Suffix (ST)

=== Prefix (ST)

=== Degree (IS)

=== Source Table (IS)

=== Assigning Authority - Namespace ID (IS)

See section, _2A.2.14.4_, "_Assigning Authority (HD)_" for definition. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70363[_User-defined Table 0363 – Assigning Authority_] in Chapter 2C, Code Tables, for suggested values. Assigning Authority is normally expressed as an HD data type, but has been flattened to 3 components here (_CNN.9_, _CNN.10_ and _CNN.11_) in this data type so that it may be fully expressed. Also note that if additional components are added to the HD data type in the future, adjustment will need to be made accordingly to this data type.

If component 1 is valued, either _CNN.8_ or _CNN.9_, or both _CNN.10_ and _CNN.11_, must be valued.

