= CSU
:render_as: Level3
:v291_section: 2A.2.12+

== CSU - channel sensitivity and units

*Attention: _Retained for backward compatibility only in version 2.7._* This is used only in the CD Channel Definition data type, which has been retained for backward compatibility only in version 2.7.

As of v2.7 a third tuple, formerly known as triplet, has been added to the CSU data type. Additionally, 3 new components were added to each tuple such that each tuple now has a total of 7 components. The Original Text component applies to the CSU as a whole.

HL7 Component Table – CSU - Channel Sensitivity and Units

[width="99%",cols="10%,7%,8%,6%,7%,7%,32%,13%,10%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |OPT |TBL# |COMPONENT NAME |COMMENTS |SEC.REF.

|1 | | |NM |R | |Channel Sensitivity | |2A.2.47

|2 | |20= |ST |C | |Unit of Measure Identifier | |2A.2.76

|3 | |199# |ST |C | |Unit of Measure Description | |2A.2.76

|4 |1..12 | |ID |C |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[0396] |Unit of Measure Coding System | |2A.2.35

|5 | |20= |ST |O | |Alternate Unit of Measure Identifier | |2A.2.76

|6 | |199# |ST |O | |Alternate Unit of Measure Description | |2A.2.76

|7 |1..12 | |ID |C |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[0396] |Alternate Unit of Measure Coding System | |2A.2.35

|8 | |10= |ST |C | |Unit of Measure Coding System Version ID | |2A.2.76

|9 | |10= |ST |O | |Alternate Unit of Measure Coding System Version ID | |2A.2.76

|10 |199 |199# |ST |O | |Original Text | |2A.2.76

|11 | |20= |ST |O | |Second Alternate Unit of Measure Identifier | |2A.2.76

|12 | |199# |ST |O | |Second Alternate Unit of Measure Text | |2A.2.76

|13 |1..12 | |ID |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[0396] |Name of Second Alternate Unit of Measure Coding System | |2A.2.35

|14 | |10= |ST |C | |Second Alternate Unit of Measure Coding System Version ID | |2A.2.76

|15 | |199= |ST |C | |Unit of Measure Coding System OID | |2A.2.76

|16 | |199= |ST |O | |Unit of Measure Value Set OID | |2A.2.76

|17 | |8= |DTM |C | |Unit of Measure Value Set Version ID | |2A.2.76

|18 | |199= |ST |C | |Alternate Unit of Measure Coding System OID | |2A.2.76

|19 | |199= |ST |O | |Alternate Unit of Measure Value Set OID | |2A.2.76

|20 | |8= |DTM |C | |Alternate Unit of Measure Value Set Version ID | |2A.2.76

|21 | |199= |ST |C | |Alternate Unit of Measure Coding System OID | |2A.2.76

|22 | |199= |ST |O | |Alternate Unit of Measure Value Set OID | |2A.2.76

|23 | |8= |ST |C | |Alternate Unit of Measure Value Set Version ID | |2A.2.76

|===

Definition: This data type defines the channel sensitivity (gain) and the units in which it is measured in a waveform result.

*Note:* Replaces the CM data type used in 7.14.1.5 OBX-5.3 where OBX-5 Observation value (*) is data type CD as of v 2.5.

=== Channel Sensitivity (NM)

=== Original Text (ST)

=== Second Alternate Unit of Measure Identifier (ST)

=== Second Alternate Unit of Measure Text (ST)

=== Name of Second Alternate Unit of Measure Coding System (ID)

Definition: Specifies the coding system for the second alternate unit of measure. Analogous to _CSU.4 Unit of Measure Coding System_. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[HL7 Table 0396 – Coding System] in Chapter 2C, Code Tables, for valid values.

This component is required when _CSU.11_ is populated. Both _CSU.13_ and _CSU.21_ may be populated. Receivers should not identify a code based on its position within the tuples (Identifier, Alternate Identifier, or Second Alternate Identifier) or position within a repeating field. Instead, the receiver should always examine the codingSystem as specified in _CSU.13_ and/or _CSU.21_ the Coding System component or the Coding System OID for the tuple.

=== Second Alternate Unit of Measure Coding System Version ID (ST)

=== Unit of Measure Coding System OID (ST)

Definition: This component contains the ISO Object Identifier (OID) for the coding system or value set named in _CSU.4_. The value for this component is 2.16.840.1.113883.12.#### where "####" is to be replaced by the HL7 table number in the case of an HL7 defined or user defined table. For externally defined code systems the OID registered in the HL7 OID registry SHALL be used.

This component is required when _CSU.2_ is populated and _CSU.4_ is not populated. Both _CSU.4_ and _CSU.15_ may be populated.

=== Unit of Measure Value Set OID (ST)

Definition: This component contains the ISO Object Identifier (OID) to allow identification of the value set from which the value in _CSU.2_ is obtained. The value for this component is 2.16.840.1.113883.12.#### where "####" is to be replaced by the HL7 table number in the case of an HL7 defined or user defined table. For externally defined value sets, the OID registered in the HL7 OID registry SHALL be used.

*Note:* If a code is provided, the meaning of the code must come from the definition of the code in the code system. The meaning of the code SHALL NOT depend on the value set. Applications SHALL NOT be required to interpret the code in light of the valueSet, and they SHALL NOT reject an instance because of the presence or absence of any or a particular value set/ value set version ID.

A value set may or need not be present irrespective of other fields.

=== Unit of Measure Value Set Version ID (DTM)

Definition: This component carries the version for the value set identified by _CSU.16_. The version is a date. The date is the date/time that the value set being used was published.

Value set version ID is required if _CSU.16_ is populated.

=== Alternate Unit of Measure Coding System OID (ST)

Definition: This component contains the ISO Object Identifier (OID) for the coding system or value set named in _CSU.7_. The value for this component is 2.16.840.1.113883.12.#### where "####" is to be replaced by the HL7 table number in the case of an HL7 defined or user defined table. For externally defined code systems the OID registered in the HL7 OID registry SHALL be used.

This component is required when _CSU.5_ is populated and _CSU.7_ is not populated. Both _CSU.7_ and _CSU.18_ may be populated.

=== Alternate Unit of Measure Value Set OID (ST)

Definition: This component contains the ISO Object Identifier (OID) to allow identification of the value set from which the value in _CSU.5_ is obtained. The value for this component is 2.16.840.1.113883.12.#### where "####" is to be replaced by the HL7 table number in the case of an HL7 defined or user defined table. For externally defined value sets, the OID registered in the HL7 OID registry SHALL be used.

A value set may or need not be present irrespective of other fields. .

*Note*: If a code is provided, the meaning of the code must come from the definition of the code in the code system. The meaning of the code SHALL NOT depend on the value set. Applications SHALL NOT be required to interpret the code in light of the valueSet, and they SHALL NOT reject an instance because of the presence or absence of any or a particular value set/ value set version ID.

=== Unit of Measure Identifier (ST) 

=== Alternate Unit of Measure Value Set Version ID (DTM)

Definition: This component carries the version for the value set identified by _CSU.19_. The version is a date. The date is the date/time that the value set being used was published.

Value set version ID is required if _CSU.19_ is populated.

=== Second Alternate Unit of Measure Coding System OID (ST)

Definition: This component contains the ISO Object Identifier (OID) for the coding system or value set named in _CSU.13_. The value for this component is 2.16.840.1.113883.12.#### where "####" is to be replaced by the HL7 table number in the case of an HL7 defined or user defined table. For externally defined code systems the OID registered in the HL7 OID registry SHALL be used.

This component is required when _CSU.11_ is populated and _CSU.13_ is not populated. Both _CSU.13_ and _CSU.21_ may be populated.

=== Second Alternate Unit of Measure Value Set OID (ST)

Definition: This component contains the ISO Object Identifier (OID) to allow identification of the value set from which the value in _CSU.11_ is obtained. The value for this component is 2.16.840.1.113883.12.#### where "####" is to be replaced by the HL7 table number in the case of an HL7 defined or user defined table. For externally defined value sets, the OID registered in the HL7 OID registry SHALL be used.

A value set may or need not be present irrespective of other fields.

Note: If a code is provided, the meaning of the code must come from the definition of the code in the code system. The meaning of the code SHALL NOT depend on the value set. Applications SHALL NOT be required to interpret the code in light of the valueSet, and they SHALL NOT reject an instance because of the presence or absence of any or a particular value set/ value set version ID.

=== Second Alternate Unit of Measure Value Set Version ID (ST)

Definition: This component carries the version for the value set identified by _CSU.22_. The version is a date. The date is the date/time that the value set being used was published.

Value set version ID is required if _CSU.22_ is populated.

=== Unit of Measure Description (ST)

=== Unit of Measure Coding System (ID)

Definition: Specifies the designated system of units. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[HL7 Table 0396 – Coding System] in Chapter 2C, Code Tables, for valid values. This component is required if the _CSU.2 Unit of Measure Identifier_ is present.

Both _CSU.4_ and _CSU.15_ may be populated. Receivers should not identify a code based on its position within the tuples (Identifier, Alternate Identifier, or Second Alternate Identifier) or position within a repeating field. Instead, the receiver should always examine the codingSystem as specified in _CSU.4_ and/or _CSU.15_, the "Coding System" component or the "Coding System OID" for the tuple.

=== Alternate Unit of Measure Identifier (ST)

Definition: A sequence of characters that uniquely identifies an alternate units designation for the channel sensitivity. Analogous to _CSU.2 Unit of Measure Identifier_.

*Usage Notes:* The Alternate Identifier is used to represent the local or user seen code as described. If present, it obeys the same rules of use and interpretation as described for component 1. If both are present, the identifiers in component 4 and component 1 should have exactly the same meaning, i.e., they should be exact synonyms.

=== Alternate Unit of Measure Description (ST)

=== Alternate Unit of Measure Coding System (ID)

Definition: Specifies the coding system for the alternate unit of measure. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[HL7 Table 0396 – Coding System] in Chapter 2C, section "Coding System Table" for valid values. Analogous to _CSU.4 Unit of Measure Coding System_.

This field is required if the _CSU.5 Alternate Unit of Measure Identifier_ is present. Both _CSU.7_ and _CSU.18_ may be populated. Receivers should not identify a code based on its position within the tuples (Identifier, Alternate Identifier, or Second Alternate Identifier) or position within a repeating field. Instead, the receiver should always examine the codingSystem as specified in _CSU.7_ and/or _CSU.18_, the "Coding System" component or the "Coding System OID" for the tuple.

=== Unit of Measure Coding System Version ID (ST)

=== Alternate Unit of Measure Coding System Version ID (ST)

