= CWE
:render_as: Level3
:v291_section: 2A.2.13+

== CWE – coded with exceptions

As of v2.7 a third tuple, formerly known as triplet, has been added to the CWE data type. Additionally, 3 new components were added to each tuple such that each tuple now has a total of 7 components. The Original Text component applies to the CWE as a whole.

HL7 Component Table - CWE – Coded with Exceptions

[width="99%",cols="10%,7%,8%,6%,7%,7%,32%,13%,10%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |OPT |TBL# |COMPONENT NAME |COMMENTS |SEC.REF.

|1 | |20= |ST |O | |Identifier | |2A.2.76

|2 | |199# |ST |O | |Text | |2A.2.76

|3 |1..12 | |ID |C |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[0396] |Name of Coding System | |2A.2.35

|4 | |20= |ST |O | |Alternate Identifier | |2A.2.76

|5 | |199# |ST |O | |Alternate Text | |2A.2.76

|6 |1..12 | |ID |C |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[0396] |Name of Alternate Coding System | |2A.2.35

|7 | |10= |ST |C | |Coding System Version ID | |2A.2.76

|8 | |10= |ST |O | |Alternate Coding System Version ID | |2A.2.76

|9 | |199# |ST |O | |Original Text | |2A.2.76

|10 | |20= |ST |O | |Second Alternate Identifier | |2A.2.76

|11 | |199# |ST |O | |Second Alternate Text | |2A.2.76

|12 |1..12 | |ID |C |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[0396] |Name of Second Alternate Coding System | |2A.2.35

|13 | |10= |ST |O | |Second Alternate Coding System Version ID | |2A.2.76

|14 | |199= |ST |C | |Coding System OID | |2A.2.76

|15 | |199= |ST |O | |Value Set OID | |2A.2.76

|16 | |8= |DTM |C | |Value Set Version ID | |2A.2.22

|17 | |199= |ST |C | |Alternate Coding System OID | |2A.2.76

|18 | |199= |ST |O | |Alternate Value Set OID | |2A.2.76

|19 | |8= |DTM |C | |Alternate Value Set Version ID | |2A.2.76

|20 | |199= |ST |C | |Second Alternate Coding System OID | |2A.2.76

|21 | |199= |ST |O | |Second Alternate Value Set OID | |2A.2.76

|22 | |8= |DTM |C | |Second Alternate Value Set Version ID | |2A.2.22

|===

*Note:* The Vocabulary TC is the steward of the CWE data type.

Definition: Specifies a coded element and its associated detail. The CWE data type is used when 1) more than one table may be applicable *or* 2) the specified HL7 or externally defined table may be extended with local values *or* 3) when text is in place, the code may be omitted.

The presence of two sets of equivalent codes in this data type is semantically different from a repetition of a CWE-type field. With repetition, several distinct codes (with distinct meanings) may be transmitted.

[#CWE_UsageNote .anchor]##*Usage Notes:* The CWE data type should be used for coded fields with one or more of the following characteristics:

____

• The identifier code (CWE.1) component is optional

• The set of allowable values from which the identifier code is drawn may be extended on a site-specific basis

• An exception identifier code may be encountered; that is, a code that is not defined in the value set (either model or site-extended).

____

This is in contrast to the CNE data type, which requires a code from a non-extendable value set be sent in the identifier code component (CNE.1) in all cases (except, of course, if the entire field is empty and defined as optional at the segment level).

The rules for populating CWE components are governed by the status of the identifier code:

[width="100%",cols="27%,24%,25%,24%",]

|===

|*Identifier Code Status* |*Identifier Code (CWE.1)* |*Descriptive Text (CWE.2)* |*Coding System (CWE.3)*

|Contained in model value set |Populated |May be populated |Must be populated with model coding system, or (not recommended) site-specific coding system that is a superset containing model values.

|Contained in site-specific extensions to model value set |Populated |May be populated |Site-specific coding system.

|Contained in neither model nor extended value sets |Not populated |May be populated with the identifier code, free-text description, or a concatenation of the two. Should be human interpretable. |Must not be populated.

|Not supplied; but descriptive text is supplied. |Not populated |May be populated with descriptive text. |Must not be populated.

|===

As an example, consider “currency” codes where:

____

• The model values are defined by the ISO 4217 value set,

• The value set is extended on site to include the code HL7 – “HL7 Drink Ticket”, and

• The data entry screen on the sending system does not enforce any edits for the currency code.

____

And so the value set used on site is:

[width="100%",cols="33%,20%,47%",]

|===

|Identifier Code Status |Identifier Code |Descriptive Text

|Model values from ISO 4217 external table |AED |United Arab Emirates, Dirhams

| |AFA |Afghanistan, Afghanis

| |ALL |Albania, Leke

| |… |

| |ZAR |South Africa, Rand

| |ZMK |Zambia, Kwacha

| |ZWD |Zimbabwe, Zimbabwe Dollars

|Site-specific extension |HL7 |HL7 Events, Drink Ticket

|===

Collectively, this value set must be referred to with a local coding system ID, because “HL7” does not exist in ISO 4217. According to the rules, the site assigns the coding system ID “99CUR” to the value set.

Based on the code and descriptive text entered by the user on the sending system, the CWE would be populated as follows:

[width="99%",cols="15%,17%,20%,24%,24%",options="header",]

|===

|*Entered by user* | |*Sent in CWE* | |

|*Code* |*Descriptive Text* |*Identifier Code (CWE.1)* |*Descriptive Text (CWE.2)* |*Coding System (CWE.3)*

|GBP |Great Britain, Pound |GBP |Great Britain, Pound |ISO4217

| | |GBP |Great Britain, Pound |99CUR (This option is NOT recommended)

|HL7 |HL7 Drink Ticket |HL7 |HL7 Drink Ticket |99CUR

|XXX |<Bogus entry> |Must not be populated |XXX |Must not be populated.

| | |Must not be populated |Bogus entry |Must not be populated.

| | |Must not be populated |XXX: Bogus entry |Must not be populated.

| | |Must not be populated |anything – or nothing. |Must not be populated.

| |Dollar |Must not be populated |Dollar |Must not be populated.

| | |Valued from HL7 Table 0353 (e.g., “U” for unknown) |Dollar |HL70353

|===

Notes:

____

{empty}1. Where multiple valid options for sending the entered data exist, each alternative is depicted as a separate row.

{empty}2. _CWE.2 - Descriptive Text_ is never required, and there are no hard and fast rules on what text may be sent in this component. Of course, common sense suggests that if valued, the text should complement the identifier code of _CWE.1_.

It follows that where _CWE.1_ cannot be valued because the entered code does not exist in the value set, the entered code _may_ be sent in _CWE.2_; with or without additional descriptive text. However, this is not required by HL7.

{empty}3. The example with GBP shows two options for the code set: ISO4217 or 99CUR. While it is now technically possible to send 99CUR on the basis that this code may exist on its own in the extended local code set, HL7 urges that where a code is a member of the standard code set, that code set should be named in _CWE.3_. HL7 intends to mandate this in a future release.

{empty}4. While there are no formal rules regarding the valuation of _CWE.2 - Descriptive Text_, it is expected that any value contained therein be meaningful to a human reader.

____

=== Identifier (ST)

Definition: The first component contains the sequence of characters (the code) that uniquely identifies the item being referenced by the CWE.2. Different coding schemes will have different elements here.

In the context of “Data Missing”, described above in the link:#CWE_UsageNote[Usage Note], refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70353[_HL7 Table 0353 – CWE Statuses_] for valid values.

HL7 Table 0353 - CWE statuses

[width="100%",cols="16%,42%,42%",options="header",]

|===

|Code |Description |Comment

|U |Unknown |

|UASK |Asked but Unknown |

|NAV |Not available |

|NA |Not applicable |

|NASK |Not asked |

|===

Refer to section 2.5.5.5 in Chapter 2, Control, for some discussion on the length of this component.

=== Second Alternate Identifier (ST)

=== Second Alternate Text (ST)

=== Name of Second Alternate Coding System (ID)

Definition: Identifies the coding scheme being used in the alternate identifier component. Analogous to _CWE.3 Name of Coding System_. See usage note in section introduction.

As of v2.7 this component is required when _CWE.10_ is populated and _CWE.20_ is not populated. Both _CWE.6_ and _CWE.17_ may be populated. Receivers should not identify a code based on its position within the tuples (Identifier, Alternate Identifier, or Second Alternate Identifier) or position within a repeating field. Instead, the receiver should always examine the coding System as specified in _CWE.12_ and/or _CWE.20_, the "Coding System" component or the "Coding System OID", for the tuple.

=== Second Alternate Coding System Version ID (ST)

=== Coding System OID (ST)

Definition: This component contains the ISO Object Identifier (OID) for the coding system or value set named in _CWE.3_. The value for this component for an HL7 or User Defined table SHALL be the value published for the code system OID for the table in _Chapter 2C Code Tables_. For externally defined code systems the OID registered in the HL7 OID registry SHALL be used.

This component is required when _CWE.1_ is populated and _CWE.3_ is not populated. Both _CWE.3_ and _CWE.14_ may be populated.

*Note*: If a code is provided, the meaning of the code must come from the definition of the code in the code system. The meaning of the code SHALL NOT depend on the value set. Applications SHALL NOT be required to interpret the code in light of the valueSet, and they SHALL NOT reject an instance because of the presence or absence of any or a particular value set/ value set version ID.

=== Value Set OID (ST)

Definition: This component contains the ISO Object Identifier (OID) to allow identification of the value set from which the value in _CWE.1_ is obtained. The value for this component is identified for each of the HL7 Tables that have values published in C__hapter 2C Code Tables__. For externally defined value sets, the OID registered in the HL7 OID registry and/or published in an HL7 balloted Implementation Guide SHALL be used.

A value set may or need not be present irrespective of other fields.

*Note:* If a code is provided, the meaning of the code must come from the definition of the code in the code system. The meaning of the code SHALL NOT depend on the value set. Applications SHALL NOT be required to interpret the code in light of the valueSet, and they SHALL NOT reject an instance because of the presence or absence of any or a particular value set/ value set version ID.

=== Value Set Version ID (DTM)

Definition: This component carries the version for the value set identified by _CWE.15_. The version is a date. The date is the date/time that the value set being used was published.

Value set version ID is required if _CWE.15_ is populated.

=== Alternate Coding System OID (ST)

Definition: This component contains the ISO Object Identifier (OID) for the coding system or value set named in _CWE.6_. Analogous to _CWE.14 Coding System OID_.

The value for this component for an HL7 or User Defined table SHALL be the value published for the code system OID for the table in _Chapter 2C Code Tables_. For externally defined code systems the OID registered in the HL7 OID registry SHALL be used.

This component is required when _CWE.4_ is populated and _CWE.6_ is not populated. Both _CWE.6_ and _CWE.17_ may be populated.

=== Alternate Value Set OID (ST)

=== Alternate Value Set Version ID (DTM)

Definition: This component carries the version for the value set identified by _CWE.18_. The version is a date. The date is the date/time that the value set being used was published.

Value set version ID is required if _CWE.18_ is populated.

=== Text (ST)

=== Second Alternate Coding System OID (ST)

Definition: This component contains the ISO Object Identifier (OID) for the coding system or value set named in _CWE.12_. Analogous to _CWE.14 - Coding System OID_.

The value for this component for an HL7 or User Defined table SHALL be the value published for the code system OID for the table in _Chapter 2C Code Tables_. For externally defined code systems the OID registered in the HL7 OID registry SHALL be used.

This component is required when _CWE.10_ is populated and _CWE.12_ is not populated. Both _CWE.12_ and _CWE.20_ may be populated.

=== Second Alternate Value Set OID (ST)

Definition: This component contains the ISO Object Identifier (OID) to allow identification of the value set from which the value in CWE.10 is obtained. The value for this component is identified for each of the HL7 Tables that have values published in Chapter 2C Code Tables. For externally defined value sets, the OID registered in the HL7 OID registry and/or published in an HL7 balloted Implementation Guide SHALL be used.

A value set may or need not be present irrespective of other fields

*Note:* If a code is provided, the meaning of the code must come from the definition of the code in the code system. The meaning of the code SHALL NOT depend on the value set. Applications SHALL NOT be required to interpret the code in light of the valueSet, and they SHALL NOT reject an instance because of the presence or absence of any or a particular value set/ value set version ID.

=== Second Alternate Value Set Version ID (DTM)

Definition: This component carries the version for the value set identified by _CWE.21_. The version is a date. The date is the date/time that the value set being used was published.

Value set version ID is required if _CWE.21_ is populated.

=== Name of Coding System (ID)

Definition: The third component contains the code for the name of the coding system from which the value in _CWE.1_ is obtained. Each coding system is assigned a unique identifier. As of v2.7 this component is required when _CWE.1_ is populated and _CWE.14_ is not populated. Both _CWE.3_ and _CWE.14_ may be populated. Receivers should not identify a code based on its position within the tuples (Identifier, Alternate Identifier, or Second Alternate Identifier) or position within a repeating field. Instead, the receiver should always examine the codingSystem as specified in _CWE.3_ and/or _CWE.14_, the "Coding System" component or the "Coding System OID" for the tuple.

Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70396[HL7 Table 0396 – Coding System] in Chapter 2C, section "Coding System Table" for valid values.

Refer to section link:#_Name_of_Coding_System (ID)[_2A.2.8.3_], "link:#_Name_of_Coding_System (ID)[_Name of Coding System (ID)_]" for a discussion of coding system conventions.

=== Alternate Identifier (ST)

Definition: A sequence of characters that uniquely identifies an alternate code. Analogous to _CWE.1- Identifier_.

*Usage Notes:* The Alternate Identifier is used to represent the local or user seen code as described. If present, it obeys the same rules of use and interpretation as described for component 1. If both are present, the identifiers in component 4 and component 1 should have exactly the same meaning, i.e., they should be exact synonyms.

=== Alternate Text (ST)

=== Name of Alternate Coding System (ID)

Definition: Identifies the coding scheme being used in the alternate identifier component. Analogous to _CWE.3 - Name of Coding System_. See usage note in section introduction.

As of v2.7 this component is required when _CWE.4_ is populated and _CWE.17_ is not populated. Both _CWE.6_ and _CWE.17_ may be populated. Receivers should not identify a code based on its position within the tuples (Identifier, Alternate Identifier, or Second Alternate Identifier) or position within a repeating field. Instead, the receiver should always examine the coding System as specified in _CWE.6_ and/or _CWE.17_, the "Coding System" component or the "Coding System OID", for the tuple.

=== Coding System Version ID (ST)

=== Alternate Coding System Version ID (ST)

=== Original Text (ST)

