= ED
:render_as: Level3
:v291_section: 2A.2.24+

== ED - encapsulated data

HL7 Component Table - ED – Encapsulated Data

[width="99%",cols="10%,7%,8%,6%,7%,7%,32%,13%,10%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |OPT |TBL# |COMPONENT NAME |COMMENTS |SEC.REF.

|1 | | |HD |O | |Source Application | |2A.2.33

|2 |4..11 | |ID |R |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70834[0834] |Type of Data | |2A.2.35

|3 | | |ID |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70291[0291] |Data Subtype | |2A.2.35

|4 |1..6 | |ID |R |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70299[0299] |Encoding | |2A.2.35

|5 | | |TX |R | |Data | |2A.2.80

|===

*Definition:* This data type transmits encapsulated data from a source system to a destination system. It contains the identity of the source system, the type of data, the encoding method of the data, and the data itself. This data type is similar to the RP (reference pointer) data type of Section _2A.2.66_, "_RP - reference pointer_," except that instead of pointing to the data on another system, it contains the data which is to be sent to that system.

=== Source Application (HD) 

=== Type of Data (ID)

Definition: Identical to “type of data” component in the reference pointer (RP) data type. See Section _2A.2.66.3_, "_Type of Data (ID)_".

Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70834[Imported Table 0834 – MIME Types] for valid values.

=== Data Subtype (ID)

Definition: Identical to “subtype” component in the reference pointer (RP) data type. See Section _2A.2.66.4_, "_Subtype (ID)_".

Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70291[_External Table 0291 - Subtype of Referenced Data_] for valid values.

=== Encoding (ID)

=== Data (TX)

Definition: Displayable ASCII characters which constitute the data to be sent from source application to destination application. The characters are limited to the legal characters of the ST data type, as defined in Section _2A.2.76_, "_ST - string data_," and, if encoded binary, are encoded according to the method of Section _2A.2.24.2_, "_Type of Data (ID)_".

If the encoding component (see Section _2A.2.24.4_, "_Encoding (ID)_") = "A" (none), then the data component must be scanned before transmission for HL7 delimiter characters, and any found must be escaped by using the HL7 escape sequences defined in Section 2.7 – "Use of escape sequences in text fields." On the receiving application, the data field must be de-escaped after being parsed.

If the encoding component ED.4 does not equal "A", then, after encoding, the (encoded) data must be scanned for HL7 delimiter characters, and any found must be escaped by using the HL7 escape sequences. Only then can the component be added to the HL7 segment/message. On the receiving application, the data field must be de-escaped after being parsed out of the message before being decoded. This can be expressed as "encode", "escape", "parse", "de-escape" or "decode".

