= FN
:render_as: Level3
:v291_section: 2A.2.30+

== FN - family name

HL7 Component Table - FN – Family Name

[width="99%",cols="10%,7%,8%,6%,7%,7%,32%,13%,10%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |OPT |TBL# |COMPONENT NAME |COMMENTS |SEC.REF.

|1 | |50# |ST |R | |Surname | |2A.2.76

|2 | |20# |ST |O | |Own Surname Prefix | |2A.2.76

|3 | |50# |ST |O | |Own Surname | |2A.2.76

|4 | |20# |ST |O | |Surname Prefix from Partner/Spouse | |2A.2.76

|5 | |50# |ST |O | |Surname from Partner/Spouse | |2A.2.76

|===

Definition: This data type allows full specification of the surname of a person. Where appropriate, it differentiates the person's own surname from that of the person's partner or spouse, in cases where the person's name may contain elements from either name. It also permits messages to distinguish the surname prefix (such as "van" or "de") from the surname root.

*Note:* Appears ONLY in the PPN, XCN and XPN.

=== Surname (ST)

=== Own Surname Prefix (ST)

Definition: Internationalization usage for Germanic languages. This component is optional. An example of a <surname prefix> is the "van" in "Ludwig van Beethoven". Since the <surname prefix> doesn't sort completely alphabetically, it is reasonable to specify it as a separate sub-component of the PN and extended PN data types (XPN and XCN).

*Note:* Subcomponents <own surname prefix>, <own surname>, <surname prefix from partner/spouse> and <surname from partner/spouse> decompose complex Germanic names such as “Martha de Mum-van Beethoven”. If these subcomponents are valued, the <surname> subcomponent should still be fully valued for backward compatibility, i.e., ^de Mum-van Beethoven&de&Mum&van&Beethoven^. +

Also, for clarity, the <last name prefix> has been renamed to <own surname prefix>.

=== Own Surname (ST)

Definition: The portion of the surname (in most Western usage, the last name) that is derived from the person's own surname, as distinguished from any portion that is derived from the surname of the person's partner or spouse. This component is optional.

If the person's surname has legally changed to become (or incorporate) the surname of the person's partner or spouse, this is the person's surname immediately prior to such change. Often this is the person's "maiden name".

=== Surname Prefix from Partner/Spouse (ST)

Definition: Internationalization usage for Germanic languages. This component is optional. An example of a <surname prefix> is the “van” in "Ludwig van Beethoven". Since the <surname prefix> doesn't sort completely alphabetically, it is reasonable to specify it as a separate sub-component of the PN and extended PN data types (XPN and XCN).

*Note:* Subcomponents <own surname prefix>, <own surname>, <surname prefix from partner/spouse> and <surname from partner/spouse> decompose complex Germanic names such as “Martha de Mum-van Beethoven”. If these subcomponents are valued, the <surname> subcomponent should still be fully valued for backward compatibility, i.e., ^de Mum-van Beethoven&de&Mum&van&Beethoven^.” +

Also, for clarity, the <last name prefix> has been renamed to <own surname prefix>.

=== Surname from Partner/Spouse (ST)

Definition: The portion of the person's surname (in most Western usage, the last name) that is derived from the surname of the person's partner or spouse, as distinguished from the part derived from the person's own surname. This component is optional.

If no portion of the person's surname is derived from the surname of the person's partner or spouse, this component is not valued. Otherwise, if the surname of the partner or spouse has legally changed to become (or incorporate) the person's surname, this is the surname of the partner or spouse immediately prior to such change.

