= MO
:render_as: Level3
:v291_section: 2A.2.41+

== MO - money

HL7 Component Table - MO – Money

[width="99%",cols="10%,7%,8%,6%,7%,7%,32%,13%,10%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |OPT |TBL# |COMPONENT NAME |COMMENTS |SEC.REF.

|1 | |= |NM |O | |Quantity | |2A.2.47

|2 |3..3 | |ID |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#ISO0913[0913] |Denomination | |2A.2.35

|===

Definition: This data type specifies an amount of money and the denomination in which it is expressed.

=== Quantity (NM)

=== Denomination (ID)

Definition: The second component is the denomination in which the quantity is expressed. The values for the denomination component are the three-character codes specified in ISO-4217. See file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#ISO0913[_Externally-defined Table 0913 – Monetary Denomination Code_].

If the denomination is not specified, "MSH-17-country code", in Chapter 2, section 2.14.9.17, is used to determine the default. Example,

|99.50^USD|

where USD is the ISO 4217 code for the U.S. American dollar.

