= RP
:render_as: Level3
:v291_section: 2A.2.66+

== RP - reference pointer

HL7 Component Table - RP – Reference Pointer

[width="99%",cols="10%,7%,8%,6%,7%,7%,32%,13%,10%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |OPT |TBL# |COMPONENT NAME |COMMENTS |SEC.REF.

|1 | |999# |ST |O | |Pointer | |2A.2.76

|2 | | |HD |O | |Application ID | |2A.2.33

|3 |4..11 | |ID |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70834[0834] |Type of Data | |2A.2.35

|4 | | |ID |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70291[0291] |Subtype | |2A.2.35

|===

*Definition:* This data type transmits information about data stored on another system. It contains a reference pointer that uniquely identifies the data on the other system, the identity of the other system, and the type of data.

=== Pointer (ST)

=== Application ID (HD)

Definition: A unique designator of the system that stores the data. It is an HD data type (See Section _2A.2.33_, "_HD - hierarchic designator_"). Application ID’s must be unique across a given HL7 implementation.

*Usage Note:* The Application ID together with the Pointer may form a Uniform Resource Identifier (URI) in accordance with RFC 2396. In this case the Application ID shall include the Scheme and Authority parts of the URI, and the Path part if that points to an application. The Pointer shall include the Query part of the URI, or the Path part if that points to an object. All delimiters between URI parts (“:”, “/”, “?”) should be included in the components.

Referenced data may be obtained by a mechanism not defined in the HL7 standard. The Scheme part of a URI in the Application ID specifies the access protocol, e.g., HTTP or FTP.

*Example 1:* A CDA document accessed by FTP:

____

|/cdasvc/u28864099/s9076500a/e77534/d55378.xml^&ftp://www.saintelsewhere.org&URI^text^x-hl7-cda-level-one|

____

*Example 2:* A DICOM image accessed by HTTP and converted to JPEG (using the ISO/DICOM WADO standard);

*Note:* the ampersands in the Pointer string are escaped to “\T\” to avoid conflict with the sub-component delimiter:

|?requestType=WADO\T\study=1.2.840.113848.5.22.9220847989\T\series=1.2.840.113848.5.22.922084798.4\T\object=1.2.840.113848.5.22.922084798.4.5^&https://www.pacs.poupon.edu/wado.jsp&URI^image^jpeg|

=== Type of Data (ID)

Definition: An ID data type that declares the general type of data. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70834[_Imported Table 0834 – MIME Types_] for valid values. Table 0834 comprises the values of MIME media types established in accordance with RFC 2046 (http://ietf.org/rfc/rfc2046.txt) and registered with the Internet Assigned Numbers Authority (http://www.iana.org/numbers.html).

*Note*: The MIME media type values are case-insensitive, in accordance with RFC 2045.

*Note: file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70191[_HL7 Table 0191- Type of Referenced Data_] is retained for backward compatibility as of v 2.6.*

=== Subtype (ID)

Definition: An ID data type declaring the format for the referenced. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70291[_Externally-defined Table 0291 – Subtype_ of Referenced Data] for valid values. Table 0291 comprises the values of MIME media subtypes established in accordance with RFC 2046 (http://ietf.org/rfc/rfc2046.txt) and registered with the Internet Assigned Numbers Authority (http://www.iana.org/numbers.html).

*Note:* the MIME media subtype values are case-insensitive, in accordance with RFC 2045.

HL7 approved "standard" extensions as defined in table 0291 are allowed.

Additional subtypes may be added to this Standard. All subtypes registered by IANA may be used by implementation agreement between cooperating parties. In addition, private, non-standard subtypes may be defined by agreement between cooperating parties. All private, non-standard subtypes should begin with the character combination “X-” to distinguish them from the standard subtypes, in accordance with RFC 2045.

