= VID
:render_as: Level3
:v291_section: 2A.2.83+

== VID – version identifier

HL7 Component Table - VID – Version Identifier

[width="99%",cols="10%,7%,8%,6%,7%,7%,32%,13%,10%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |OPT |TBL# |COMPONENT NAME |COMMENTS |SEC.REF.

|1 |3..5 | |ID |R |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70104[0104] |Version ID | |2A.2.35

|2 | | |CWE |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70399[0399] |Internationalization Code | |2A.2.13

|3 | | |CWE |O | |International Version ID | |2A.2.13

|===

=== Version ID (ID)

=== Internationalization Code (CWE)

Definition: Used to identify the international affiliate country code. The values to be used are those of ISO 3166 -1:1977. The ISO 3166 table has three separate forms of the country code: HL7 specifies that the 3-character (alphabetic) form be used for the country code.

Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70399[_HL7 Table 0__399 - Country Code_] in Chapter 2C for the 3-character codes as defined by ISO 3166 table.

=== International Version ID (CWE)

