= XCN
:render_as: Level3
:v291_section: 2A.2.88+

== XCN - extended composite ID number and name for persons

HL7 Component Table - XCN – Extended Composite ID Number and Name for Persons

[width="99%",cols="10%,7%,8%,6%,7%,7%,32%,13%,10%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |OPT |TBL# |COMPONENT NAME |COMMENTS |SEC.REF.

|1 | |15= |ST |C | |Person Identifier | |2A.2.76

|2 | | |FN |C | |Family Name | |2A.2.30

|3 | |30# |ST |O | |Given Name | |2A.2.76

|4 | |30# |ST |O | |Second and Further Given Names or Initials Thereof | |2A.2.76

|5 | |20# |ST |O | |Suffix (e.g., JR or III) | |2A.2.76

|6 | |20# |ST |O | |Prefix (e.g., DR) | |2A.2.76

|7 | | | |W | |Degree (e.g., MD) |withdrawn as of v2.7 |2A.2.36

|8 | | |CWE |B |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70297[0297] |Source Table | |2A.2.36

|9 | | |HD |C |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70363[0363] |Assigning Authority | |2A.2.33

|10 |1..5 | |ID |C |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70200[0200] |Name Type Code | |2A.2.35

|11 |1..4 | |ST |O | |Identifier Check Digit | |2A.2.76

|12 |3..3 | |ID |C |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70061[0061] |Check Digit Scheme | |2A.2.35

|13 |2..5 | |ID |C |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70203[0203] |Identifier Type Code | |2A.2.35

|14 | | |HD |O | |Assigning Facility | |2A.2.33

|15 |1..1 | |ID |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70465[0465] |Name Representation Code | |2A.2.35

|16 | | |CWE |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70448[0448] |Name Context | |2A.2.13

|17 | | | |W | |Name Validity Range |withdrawn as of v2.7 |2A.2.20

|18 |1..1 | |ID |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70444[0444] |Name Assembly Order | |2A.2.35

|19 | |8= |DTM |O | |Effective Date | |2A.2.22

|20 | |8= |DTM |O | |Expiration Date | |2A.2.22

|21 | |199# |ST |O | |Professional Suffix | |2A.2.76

|22 | | |CWE |C | |Assigning Jurisdiction | |2A.2.13

|23 | | |CWE |C | |Assigning Agency or Department | |2A.2.13

|24 | |4= |ST |O | |Security Check | |2.A.74

|25 |3..3 | |ID |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70904[0904] |Security Check Scheme | |2.A.35

|===

*Note:* Replaces CN data type as of v 2.3.

This data type is used extensively appearing in the PV1, ORC, RXO, RXE, OBR and SCH segments, as well as others, where there is a need to specify the ID number and name of a person.

Example without assigning authority and assigning facility:

|1234567^Everyman^Adam^A^III^DR^^ADT01^^L^4^M11^MR|

Examples with assigning authority and assigning facility:

Dr. Harold Hippocrates’ provider ID was assigned by the Provider Master and was first issued at Good Health Hospital within the Community Health and Hospitals System. Since IS table values (first component of the HD) were not used for assigning authority and assigning facility, components 2 and 3 of the HD data type are populated and demoted to sub-components as follows:

12188^Hippocrates^Harold^H^IV^Dr^^^&Provider Master.Community Health and Hospitals&L^L^9^M10^DN^&Good Health Hospital.Community Health and Hospitals&L^A

Ludwig van Beethoven's medical record number was assigned by the Master Patient Index and was first issued at Fairview Hospital within the University Hospitals System.

10535^van Beethoven&van^Ludwig^A^III^Dr^^^&MPI.Community Health and Hospitals&L^L^3^M10^MR^& Good Health Hospital.Community Health and Hospitals&L^A

=== Person Identifier (ST)

Definition: This component carries the Person Identifier itself. XCN.1, in conjunction with XCN.9 uniquely identifies the entity/person.

_XCN.1_ is required if _XCN.2_ is not populated. Both may be populated.

=== Name Type Code (ID)

Definition: A code that represents the type of name. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70200[_HL7 Table 0200 - Nam__e Type_] for valid values. See Section _2A.2.90.7_, "_Name Type Code (ID)_".

As of v 2.7, _XCN.10_ is conditional. It is required if _XCN.2_ is populated.

=== Identifier Check Digit (ST)

=== Check Digit Scheme (ID)

Definition: Contains the code identifying the check digit scheme employed.

Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70061[_HL7 T__able 0061 - Check Digit Scheme_] for valid values.

=== Identifier Type Code (ID)

Definition: A code corresponding to the type of identifier. In some cases, this code may be used as a qualifier to the <assigning authority> component. Refer to E:\\V2\\v2.9 final Nov from Frank\\V29_CH02C_Tables.docx#HL70203[_HL7 Table 0203 - Identifier Type_] for suggested values.

As of v 2.7, _XCN.13_ is conditional. It is required if _XCN.1_ is populated.

=== Assigning Facility (HD)

Definition: The place or location identifier where the identifier was first assigned to the person. This component is not an inherent part of the identifier but rather part of the history of the identifier: as part of this data type, its existence is a convenience for certain intercommunicating systems.

*Note:* When the HD data type is used in a given segment as a component of a field of another data type, file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70300[_User-defined Table 0300 - Nam__espace ID_] (referenced by the first sub-component of the HD component) may be re-defined (given a different user-defined table number and name) by the technical committee responsible for that segment.

=== Name Representation Code (ID)

Definition: Different <name/address types> and representations of the same <name/address> should be described by repeating of this field, with different values of the <name/address type> and/or <name/address representation> component.

*Note:* This new component remains in “alphabetic” representation with each repetition of the field using these data types. I.e., even though the name may be represented in an ideographic character set, this component will remain represented in an alphabetic character set.

Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70465[_HL7 Table 0465 – Name/address Representation_] for valid values.

In general this component provides an indication of the representation provided by the data item. It does not necessarily specify the character sets used. Thus, even though the representation might provide an indication of what to expect, the sender is still free to encode the contents using whatever character set is desired. This component provides only hints for the receiver, so it can make choices regarding what it has been sent and what it is capable of displaying.

=== Name Context (CWE)

=== Name Validity Range 

*Attention:* _The XCN.17 component was deprecated as of v2.5 and the detail was withdrawn and removed from the standard as of v 2.7._ Refer to _XCN.19 Effective Date_ and _XCN.20 Expiration Date_ instead.

This component contains the start and end date/times that define the period during which this name was valid.

=== Name Assembly Order (ID)

=== Effective Date (DTM)

=== Family Name (FN) 

Definition: This component allows full specification of the surname of a person. Where appropriate, it differentiates the person's own surname from that of the person's partner or spouse, in cases where the person's name may contain elements from either name. It also permits messages to distinguish the surname prefix (such as "van" or "de") from the surname root. See section _2A.2.30_, "_FN - family name_".

_XCN.2_ is required if _XCN.1_ is not populated. Both may be populated.

=== Expiration Date (DTM)

=== Professional Suffix (ST)

=== Assigning Jurisdiction (CWE)

Definition: The geo-political body that assigned the identifier in _XCN.1_.

See section, _2A.2.14.9_, "_Assigning Jurisdiction (CWE)_" for further detail.

As of v 2.7, the Assigning Jurisdiction is conditional. It is required if _XCN.1_ is populated and neither _XCN.9_ nor _XCN.23_ are populated. All 3 components may be populated. The reader is referred to _XCN.9_ if there is a need to transmit this information as an OID.

=== Assigning Agency or Department (CWE)

Definition: The agency or department that assigned the identifier in _XCN.1_.

See section _2A.2.14.10_, "_Assigning Agency or Department (CWE)_" for further details.

As of v 2.7, the Assigning Jurisdiction is conditional. It is required if _XCN.1_ is populated and neither _XCN.9_ nor _XCN.22_ are populated. All 3 components may be populated. The reader is referred to _XCN.9_ if there is a need to transmit this information as an OID.

=== Security Check (ST)

=== Security Check Scheme (ID)

Definition: This component is used to transmit information intended to validate the veracity of the supplied identifier or the presenter of the identifier. For example, this component may be used to ensure that the presenter of a credit card is an authorized user of that card.

Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70904[_HL7 Table 0904 - Security Check Scheme_] for valid values

=== Given Name (ST)

=== Second and Further Given Names or Initials Thereof (ST) 

=== Suffix (ST)

=== Prefix (ST) 

=== Degree 

=== Source Table (CWE)

*Attention*: _Retained for backwards compatibility only as of v 2.7_. The reader is referred to _XCN.9_ instead.

file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70297[_User-de__fined Table 0297 – CN ID_] source is used as the HL7 identifier for the user-defined table of values for this component. Used to delineate the first component.

=== Assigning Authority (HD)

Definition: The assigning authority is a unique identifier of the system (or organization or agency of department) that creates the data. file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70363[_User-defined Table 0363 – Assig__ning Authority_] is used as the HL7 identifier for the user-defined table of values for the first sub-component of the HD component, <namespace ID>.

As of v 2.7, the Assigning Authority is conditional. It is required if _XCN.1_ is populated and neither _XCN.22_ nor _XCN.23_ are populated. All 3 components may be populated. No assumptions can be safely made based on position or sequence. Best practice is to send an OID in this component when populated.

The reader is referred to _XCN.22_ and _XCN.23_ if there is a need to transmit values with semantic meaning for an assigning jurisdiction or assigning department or agency in addition to, or instead of, an assigning authority. However, all 3 components may be valued. If, in so doing, it is discovered that the values in _XCN.22_ and/or _XCN.23_ conflict with _XCN.9_, the user would look to the Message Profile or other implementation agreement for a statement as to which takes precedence.

*Note:* When the HD data type is used in a given segment as a component of a field of another data type, file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70300[_User-defined Table 0300 - Namespa__ce I__D_] (referenced by the first sub-component of the HD component) may be re-defined (given a different user-defined table number and name) by the technical committee responsible for that segment.

By site agreement, implementors may continue to use file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70300[_User-defined Table 0300 – Namespace ID_] for the first sub-component.

