= XTN
:render_as: Level3
:v291_section: 2A.2.91+

== XTN - extended telecommunication number

HL7 Component Table - XTN – Extended Telecommunication Number

[width="99%",cols="10%,7%,8%,6%,7%,7%,32%,13%,10%",options="header",]

|===

|SEQ |LEN |C.LEN |DT |OPT |TBL# |COMPONENT NAME |COMMENTS |SEC.REF.

|1 | | | |W | |Telephone Number | |2A.2.76

|2 |3..3 | |ID |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70201[0201] |Telecommunication Use Code | |2A.2.35

|3 |2..8 | |ID |R |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70202[0202] |Telecommunication Equipment Type | |2A.2.35

|4 | |199= |ST |C | |Communication Address | |2A.2.76

|5 | |3= |SNM |O | |Country Code | |2A.2.47

|6 | |3= |SNM |O | |Area/City Code | |2A.2.47

|7 | |9= |SNM |C | |Local Number | |2A.2.47

|8 | |5= |SNM |C | |Extension | |2A.2.47

|9 | |199# |ST |O | |Any Text | |2A.2.76

|10 | |4= |ST |O | |Extension Prefix | |2A.2.76

|11 | |6= |ST |O | |Speed Dial Code | |2A.2.76

|12 | |199# |ST |C | |Unformatted Telephone Number | |2A.2.76

|13 | | |DTM |O | |Effective Start Date | |2A.2.22

|14 | | |DTM |O | |Expiration Date | |2A.2.22

|15 | | |CWE |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70868[0868] |Expiration Reason | |2A.2.13

|16 | | |CWE |O |file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70618[0618] |Protection Code | |2A.2.13

|17 | | |EI |O | |Shared Telecommunication Identifier | |2A.2.25

|18 | |2= |NM |O | |Preference Order | |2A.2.47

|===

Example 1: A Work fax number

^WPN^FX^^^734^6777777

Example 2: Telephone number with extension

^WPN^PH^^^734^6777777^1

Example 2: Telephone number with internal code. In this example, assume that a corporation's telephone system supports a full external telephone number (area code and telephone number). It also supports internal dialing standards that assign a code to each facility and an extension to each telephone (which happens to be the last 4 digits of the external telephone number, by convention).

So, if the Los Angeles facility were assigned code 333, and if the "outside" telephone number at the LA office is (626) 555-1234, the components would be:

[width="100%",cols="42%,58%",options="header",]

|===

|Component |Value

|area/city code |626

|phone number |555-1234

|extension |1234

|extension prefix |333

|===

The field would be transmitted as follows:

^WPN^PH^^^626^5551234^1234^333

Example 3: speed dial. In this example, assume that a corporation's telephone system supports speed dialing numbers. For example, suppose that a corporation has a contract with a travel agency, whose external number is 1-610-555-1234. Since it is so frequently dialed, the company assigns a speed code: #6098. The components would be:

[width="100%",cols="42%,58%",options="header",]

|===

|Component |Value

|Area/city code |610

|Phone number |555-1234

|Speed Dial |#6098

|===

The field would be transmitted as follows:

^WPN^PH^^^610^5551234^^^#6098

Example 4: home e-mail address. In this example, assume that a person has a primary home e-mail address such as someone@somewhere.com. The components would be:

[width="100%",cols="56%,44%",options="header",]

|===

|Component |Value

|Telecommunication Use Code |PRN

|Telecommunication Equipment Type |Internet

|Communication Address |someone@somewhere.com

|===

The field would be transmitted as follows:

^PRN^Internet^someone@somewhere.com

Example 5: work e-mail address. In this example, assume that a person has a work e-mail address such as someone@somewhere.com. The components would be:

[width="100%",cols="54%,46%",options="header",]

|===

|Component |Value

|Telecommunication Use Code |WPN

|Telecommunication Equipment Type |Internet

|Communication Address |someone@somewhere.com

|===

The field would be transmitted as follows:

^WPN^Internet^someone@somewhere.com

=== Telephone Number 

=== Extension Prefix (ST)

Definition: The characters established within a company’s internal telephone system network used as a prefix to the Extension component for internal dialing.

*Note:* The use of Extension Prefix requires that the Extension component be valued and that digits, as well as special characters (e.g., *, #) may be used.

=== Speed Dial Code (ST)

Definition: The characters established within a company’s internal telephone system used in place of the (external) telephone number to facilitate calling because its length is shorter than that of the telephone number.

*Note:* Digits, as well as special characters (e.g., *, #) may be used.

=== Unformatted Telephone Number (ST)

Definition: An expression of the telephone number as an unparsable string. The Unformatted Telephone number is required when, and allowed only if, _XTN.4_ and _XTN.7_ are not populated.

The phone number was entered as free text and sending system does not know how to parse it.

Example: |^^^^^^^^^^^1-800-Dentist|

=== Effective Start Date (DTM)

=== Expiration Date (DTM)

=== Expiration Reason (CWE)

=== Protection Code (CWE)

Definition: Indicates whether this information is considered sensitive or should be protected in some way. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70618[_User-defined table 0618 - Protection Code_] for suggested values.

The specific set of codes and appropriate handling of such telecommunications addresses will vary by jurisdiction and is subject to site-specific negotiation. For example, a provider address marked as 'unlisted' might not be printed in an internal address listing.

=== Shared Telecommunication Identifier (EI)

Definition: A unique identifier for the phone number or e-mail address.

This component allows a phone number to be uniquely identified, and enables the linking of a single phone number to multiple people and contexts. For example, each member of a family living at the same location would share the same phone number, having the same identifier. A correction to the phone number of one family member could be automatically propagated to other members of the family.

HL7 does not assume responsibility for the processing rules for this component.

=== Preference Order (NM)

Definition: For an entity having multiple telecommunication addresses, indicates which is the "most preferred" (lowest number) to "least preferred" (highest number).

If the preference order is unique across all usages for a given type, then it indicates the preference across all usages, (e.g. first try my home number, then my business number). If the preference order is unique across all usages and types, then it indicates the preference across all types of telecommunication addresses. (E.g., first try my phone; if that doesn't work, use my pager.) Otherwise, the preference order is assumed to only apply within a specific type and usage.

Preference order numbers need not be sequential (i.e., three numbers with the priority orders of 0, 5 and 15 are legitimate). The preference order numbers must be non-negative.

=== Telecommunication Use Code (ID) 

=== Telecommunication Equipment Type (ID)

=== Communication Address (ST)

*Note*: This component is required if, and only allowed if, XTN.7 or XTN.12 are not populated.

*Note*: If any of the HL7 delimiters are found in the Communication Address, such as @, the appropriate HL7 escape sequence SHALL be used when encoding an Internet address (see Chapter 2, "Control", section 2.7.1, "Formatting Codes").

=== Country Code (SNM)

=== Area/City Code (SNM)

Definition: The numeric code to access telephone services in another area/city within a country. This number historically needs not be dialed if the caller is located in the same area/city as the phone number of the called party.

The use and size of area/city codes is however country specific: some countries do not use area/city codes, or the use of area/city codes may be mandatory when dialing, or area/city codes may be used to group phone numbers based on other criteria than geographic location, such as cell-phone area/city-codes, or free information numbers (e.g., 800 numbers).

Most countries have a prefix for Area/City codes which only has to be dialed if one doesn't use a country code. This prefix (mostly "0", sometimes "9") should be omitted from the content of this field. If the prefix for the Area/Code is also mandatory if one uses the country code (e.g., in Italy) then this field should also contain the prefix.

=== Local Number (SNM)

Definition: The numeric code used to contact the called party, exclusive of country and area/city codes. The Local Number is required when, and allowed only if, _XTN.4_ and _XTN.12_ are not populated.

The size of the Local Number is country specific.

*Note*: The Local Number does not include the numeric codes that have to be dialed once a connection has been established. Examples include (automated) organizational phone systems which allow external callers to dial additional numeric codes. These additional numeric codes should be specified as an extension.

=== Extension (SNM)

=== Any Text (ST)

Definition: Contains comments with respect to the telephone number.

Example: |^^^^^^^^Do not use after 5PM|

