= Examples
:render_as: Level4
:v291_section: 4A.5+

== Pharmacy/Treatment Message Examples 

=== Example of various levels of coding in an order

The order "_give 500 mg Ampicillin P.O. Q6H for 10 days for a total of 40 tablets_" is sent to the RX application from the OE application. This order can be coded with various levels of precision by an ordering application:

{empty}a) E-mail only version (uses only free text, _RXO-6-provider's pharmacy/treatment instructions_ or _RXO-7-provider's administration instructions_ only); fully encoded version must be re-entered or verified manually by the pharmacy or treatment application.

{empty}b) With _RXO-2-requested give amount-minimum_, _RXO-4-requested give units_, and _ORC-7-quantity/timing coded_, and _RXO-1-requested give code_ as free text.

{empty}c) With _RXO-1-requested give code_, _RXO-2-requested give amount-minimum_, _RXO-4-requested give units_, and _ORC-7-quantity/timing coded_, but where _RXO-1-requested give code_ does not include units.

{empty}d) With _RXO-1-requested give code_, _RXO-2-requested give amount-minimum_, _RXO-4-requested give units_, and _ORC-7-quantity/timing coded_, and where _RXO-1-requested give code_ does include units.

In this case, the units are optional. The rule for this case (on orders, dispense results, give results, and administration results) is as follows: if units are coded, they override or supersede the units value implied by the give code.

{empty}e) The E-mail only version of the order: no coded fields exist in the RXO.

MSH|^&~\|Pharm|GenHosp|CIS|GenHosp|2006052911150700||OMP^O09^OMP_O09|...<cr>

PID|...<cr>

ORC|NW|1000^OE||||E|...<cr>

RXO||||||500 mg Polycillin Q6H for 10 days, dispense 40 Tablets|...<cr>

{empty}f) A partially coded version of the order. This version has the _RXO-2-requested give amount-minimum_, _RXO-4-requested give units_, and _ORC-7-quantity/timing coded_, but the _RXO-1-requested give code_ as free text.

MSH|^&~\|Pharm|GenHosp|CIS|GenHosp|2006052911150700||OMP^O09^OMP_O09|...<cr>

PID|...<cr>

ORC|NW|1000^OE||||E|^Q6H^D10^^^R|...<cr>

RXO|^Polycillin 500 mg TAB^|500||MG|||||Y||40|...<cr>

RXR|PO|...<cr>

{empty}g) A more completely coded version of the order, with the _RXO-1-requested give code_, _RXO-2-requested give amount-minimum_, _RXO-4-requested give units_, and _ORC-7-quantity/timing coded_, but where _RXO-1-requested give code_ does not imply units.

MSH|^&~\|Pharm|GenHosp|CIS|GenHosp|2006052911150700||OMP^O09^OMP_O09|...<cr>

PID|...<cr>

ORC|NW|1000^OE||||E|^Q6H^D10^^^R|...<cr>

RXO|RX1001^Polycillin^L|500||MG|||||Y||40|...<cr>

RXR|PO|...<cr>

{empty}h) A completely encoded version, with the _RXO-1-requested give code_, _RXO-2-requested give amount-minimum_, _RXO-4-requested give units_, and _ORC-7-quantity/timing coded_, and where _RXO-1-requested give code_ does imply units.

MSH|^&~\|Pharm|GenHosp|CIS|GenHosp|2006052911150700||OMP^O09^OMP_O09|...<cr>

PID|...<cr>

ORC|NW|1000^OE||||E|^Q6H^D10^^^R|...<cr>

RXO|RX1001^Polycillin 500 mg TAB^L|500||MG|||||G||40|...<cr>

RXR|PO|...<cr>

{empty}i) Pharmacy or treatment supplier's encoded version (RDE message) sent to nursing application (a generic substitution).

MSH|^&~\|Pharm|GenHosp|CIS|GenHosp|2006052911150700||RDE^O11^RDE_O11|...<cr>

PID|...<cr>

ORC|RE|1000^OE|9999999^RX|||E|^Q6H^D10^^^R|...<cr>

RXE|^^^200612100600^^R|0047-0402-30^Ampicillin 250 MG

TAB^NDC|2||TAB|||||G|80||||123456|rx#1001|...<cr>

RXR|PO|...<cr>

{empty}j) Pharmacy or treatment supplier's dispense results (RDS message).

MSH|...<cr>

PID|...<cr>

ORC|RE|1000^OE|9999999^RX|||E|^Q6H^D10^^^R|...<cr>

RXD|1|0047-0402-30^Ampicillin 250 MG TAB^NDC|199012100400|8|TAB||RX#1001|

123456|G|8|...<cr>

{empty}k) Pharmacy or treatment supplier's give results (RGV message).

MSH|^&~\|Pharm|GenHosp|CIS|GenHosp|2006052911150700||RGV^O15^RGV_O15|...<cr>

PID|...<cr>

ORC|RE|1000^OE|9999999^RX|||E|^Q6H^D10^^^R|...<cr>

RXG|1|1|^^200612100600^^R|0047-0402-30^Ampicillin 250 MG TAB^NDC|500||MG|||G|...<cr>

RXR|PO|...<cr>

{empty}l) Nursing application Medications Administration results to pharmacy, treatment, or Order Entry application.

MSH|^&~\|Pharm|GenHosp|CIS|GenHosp|2006052911150700||RAS^O17^RAS_O17|...<cr>

PID|...<cr>

ORC|RE|1000^OE|9999999^RX|||E|^Q6H^D10^^^R|...<cr>

RXA|1|1|200612100615||0047-0402-30^Ampicillin 250 MG TAB^NDC|2|TAB|...<cr>

RXR|PO|...<cr>

=== RXO segment field examples

==== RXO-1 Requested Give code example

==== RXO-18 and RXO-19 Requested Strength and Strength Unit examples

The need for strength and strength unit fields in addition to the amount and amount units fields included in various RX_ segments requires explanation. Physicians can write a prescription for a drug such as Ampicillin in two ways. One way would be: "Ampicillin 250 mg capsules, 2 capsules four times a day." In this case the give amount would be 2, the give units would be capsules, the strength would be 250 and the strength units would milligrams.

ORC|||||||1^QID|...<cr>

RXO|01200020200105^Ampicillin 250 mg capsule^GPI^00047040230^Ampicillin 250 mg caps^NDC|2||caps^capsule^FDB||||||||||||||250|mg|...<cr>

However, the provider could also write the prescription as "Ampicillin 500 mg four times a day." In this case the give amount would be 500 and the give units would be milligrams. The strength would not be reported in the RXO segment because it is not specified; the drug could be given in two 250 mg caps or one 500 mg cap. But the pharmacist would dispense a specific capsule size and would record the strength in the RXE segment as 250 or 500, depending upon which pill size was dispensed.

ORC|||||||1^QID|...<cr>

RXO|012000202001^Ampicillin capsule^GPI |500||mg^milligram^ISO||...<cr>

=== RXD segment field examples

==== RXD-4 and RXD-5 Dispense amount and Actual dispense units

The RXD-4 and RXD-5 together might say

100 tabs:

RXD||||100|TAB^tablet^FDB|...<cr>

Or, 100 each

RXD||||100|EA^each^FDB|...<cr>

Or, perhaps a volume, 3 liters

RXD||||3|L^liter^ISO|...<cr>

==== Actual dispense amount, Actual dispense units, Actual strength, Actual strength units

For example, the RXD-4, RXD-5, RXD-16 and RXD-17 together might say

100 tabs of 240 mg strength:

RXD||||100|tab^tablet^FDB|||||||||||240|mg|...<cr>

Or, 100 each of 60 units per cc

RXD||||100|EA||||||||||||60|iu/ml^^ISO+|...<cr>

Or, perhaps a volume, 3 liters with 60 grams per liter

RXD||||3|L^liter^ISO|||||||||||60|g/L^^ISO+|...<cr>

==== Valuing the Dispense Package Size Unit 

If the package given to the patient is 2, 4 ounce bottles with a strength of 100/5ml, but the cough suppressant is stocked in 1 gallon bottles, then the field contains 1 gallon.

RXD||||8|ounce^^ISO|||||||||||20|mg/ml|||||1|gal^gallon^ISO|...<cr>

If one were to dispense Mevacor 100 tablets with a strength of 20 mg/tablet, and the package from the manufacturer is a 60 tablet package, then the fields reflect 60 tablets (the size of the package stocked by the pharmacy).

RXD||||100|tab^^FDB|||||||||||20|mg|||||60|tab|...<cr>

=== RDS with FT1 segments example

Example: Adam Everyman appears in the Pharmacy with a prescription for Veramil 120 mgm B.I.D. The prescription is filled and the $5 co-pay is collected. The following RDS message is generated:

MSH|^&~\|Pharm|GenHosp|IE||2006052911150700||RDS^O13^RDS_O13||...<cr>

PID|||444-33-3333^^^MPI&GenHosp&L^MR||Everyman^Adam||19600614|M||C|2222 Home St^^Anytown^US^12345||^^^^^555^5552004| ...<cr>

ORC|RE||89968665||||||2006052910300700|||444-44-4444^HIPPOCRATES^HAROLD^^^^MD||^^^^^555^ 5551004|...<cr>

RXE|1^BID^^20060529|^Verapamil|120||mg^milligram^FDB.MDDB||...<cr>

RXD|1|00378112001^Verapamil Hydrochloride 120 mg TAB^NDC |200605291115-0700|100|||1331665|3|...<cr>

RXR|PO|...<cr>

FT1|1|||200605291115-0700||CO^Co-Pay^HL70017 |00378112001^Verapamil Hydrochloride 120 mg TAB^NDC |||1|5&USD^TP|...<cr>

FT1|2|||200605291115-0700||PY^Payment^HL70017 |00378112001^Verapamil Hydrochloride 120 mg TAB^NDC |||1|5&USD|...<cr>

=== Alternating IV order messages

Encoding Note: For readability, these examples do not show encoding of the subcomponents of the Give Codes (CWE data type) in the RXC and RXO segments. In practice, the subcomponents should be encoded as described in the HL7 specification.

{empty}a) Example #1

D5/0.45NaCl 1000mL with 20mEq KCl in every 3rd bottle. Start the KCl in the 3rd bottle of this order. Run in at a rate of 100mL/hr.

(Other message data: placer order #123, placer application ID=SMS, interval=continuous, start date/time=11/28/94 0900, no stop date/time, priority=Routine, order sequencing=Cyclical.)

This order may be expressed using a parent/child relationship. The parent order consists of an ORC (and a RXO, incompletely elaborated in this example) that contains order level information. The repeating bottle cycle of D5/0.45NaCl 1000mL followed by D5/0.45NaCl 1000mL followed by D5/0.45NaCl + 20mEq KCL 1000mL is represented by three child segments. The placer system may be treating this as a single order with two bottles, A (D5/0.45NaCl 1000mL @ 100mL/hr) and B (D5/0.45NaCl + 20mEq KCL 1000mL @ 100mL/hr), repeating in the cycle of A-A-B.

The parent:

ORC|NW|123^SMS|||||1^C^^200611280900^^R^^^^C|...<cr>

RXO|Cyclic IV|...<cr>

The first child:

ORC|CH|123A1^SMS|||||1^C^^^^^^^^C&123B&SMS&&&*ES+0M|123|...<cr>

RXO Segment, Requested Give Amount-Minimum: ...|100||ML|...

Requested Give Per (Time Unit): ...|H1|...<cr>

RXR|IV|...<cr>

RXC|B|D5/.45NACL|1000|ML|...<cr>

The second child:

ORC|CH|123A2^SMS|||||1^C^^^^^^^^C&123A1&SMS&&&ES+0M|123|...<cr>

RXO Segment, Requested Give Amount-Minimum: ...|100||ML|...

Requested Give Per (Time Unit): ...|H1|...<cr>

RXR|IV|...<cr>

RXC|B|D5/.45NACL|1000|ML|...<cr>

The third child:

ORC|CH|123B^SMS|||||1^C^^^^^^^^C&123A2&SMS&&&#ES+0M|123|...<cr>

RXO Segment, Requested Give Amount-Minimum: ...|100||ML|...

Requested Give Per (Time Unit): ...|H1|...<cr>

RXR|IV|...<cr>

RXC|B|D5/.45NACL|1000|ML|...<cr>

RXC|A|KCL|20|MEQ|...<cr>

Discussion points:

Placer Order Number - Three alternatives must be discussed for placer order number.

{empty}1) Each child could have its own placer order number.

{empty}2) Each child could have the order number of the parent plus some appended identifier (for examples, 123A or 123.A or 123.1 etc.) that labels each child or each unique combination of ingredients.

{empty}3) In addition to the appended identifier discussed in 'B' above, a further suffix could be attached to uniquely identify each repetition of a particular member of the sequence. The example (a cycle of bottles 'A' and 'B' in the sequence A-A-B) identified the order numbers of the children as 123A1, 123A2, and 123B, thereby enabling the quantity/timing to be completely unambiguous. This could be expressed many other ways, such as 123A.1 or 123.A.1 or 123.A#1 etc. HL7 does not specify a format for the expression of order number suffixes, nor does it specify a delimiter to use for such a purpose.

Sequence Condition Value - In this example, the first child contains an asterisk (*) as the first character of the Sequence Condition Value and the third (last) child contains a pound sign (#).

The asterisk and pound sign are important for designating the first and last bottles especially when children are sent in separate messages, although this example is not constructed that way.

Note that computing the duration of the bottle is dependent upon the presence of [.underline]#all# of the following fields:

RXO-2-requested give amount-minimum

RXO-4-requested give units

RXC-3-component amount

RXC-4-component units

For cyclic IV orders, these fields are all required in order to determine how long each occurrence of a child will last.

While HL7 allows either sending the parent and children in one message or sending the parent and children in separate messages, it appears simpler and therefore recommended to have the parent and all children included in a single message. The example is constructed that way.

{empty}b) Example #2

D5W + 40mEq KCl 1000mL alternating with D5/LR + 20mEq KCl 1000mL at 125mL/hr

(Other message data: placer order #124, placer application ID=SMS, interval=continuous, start date/time=11/28/94 0900, no stop date/time, priority=Routine, order sequencing=Cyclical)

This example is a variation on the first example where two different base solutions are used. In this example, the placer system deals with this as one order with two alternating bottles, A (D5W + 40mEq KCl 1000mL @ 125mL/hr) and B (D5/LR + 20mEq KCl 1000mL @ 125mL/hr) in the cycle A-B. The principles discussed in Example #1 apply equally to this example.

The parent:

ORC|NW|124^SMS|||||1^C^^200611280900^^R^^^^C|...<cr>

RXO|Cyclic IV|...<cr>

The first child:

ORC|CH|124A^SMS|||||1^C^^^^^^^^C&124B&SMS&&&*ES+0M|124|...<cr>

RXO Segment, Requested Give Amount-Minimum: ...|125||ML|...

Requested Give Per (Time Unit): ...|H1|...<cr>

RXR|IV|...<cr>

RXC|B|D5W|1000|ML|...<cr>

RXC|A|KCL|40|MEQ|...<cr>

The second child:

ORC|CH|124B^SMS|||||1^C^^^^^^^^C&124A&SMS&&&#ES+0M|124|...<cr>

RXO Segment, Requested Give Amount-Minimum: ...|125||ML|...

Requested Give Per (Time Unit): ...|H1|...<cr>

RXR|IV|...<cr>

RXC|B|D5/LR|1000|ML|...<cr>

RXC|A|KCL|20|MEQ|...<cr>

{empty}c) Example #3

D5/0.45NaCl 1000mL with 20mEq KCl in every 3rd bottle. Start the KCl in the 3rd bottle of this order. Add 10mL of multi-vitamins to the one bag daily. Run in at a rate of 100mL/hr.

(Other message data: placer order #134, placer application ID=SMS, interval=continuous, start date/time=11/28/94 0900, no stop date/time, priority=Routine, order sequencing=Cyclical. Note that the encoding of the multi-vitamins statement in the above order, adding multi-vitamins to one IV bag each day, may vary by institution to put it into the first or last bottle of the day.)

This order may be expressed using a parent/child relationship. The parent order consists of an ORC (and a RXO, although one is not completely elaborated in this example) that contains order level information. The repeating bottle cycle of D5/0.45NaCl 1000mL followed by D5/0.45NaCl 1000mL followed by D5/0.45NaCl + 20mEq KCL 1000mL is represented by three child segments. This order is complicated by the request to add one component into any one of the three repeating bottles, depending upon which of the bottles will occur first on any particular day. Further complicating this order is a rate of infusion (10 hours for a 1000mL bottle) which results in a fractional number of daily administrations. Most legacy systems have a great deal of trouble accommodating orders like this within their existing database structures; however there a few vendors who now are able to handle the situation. The placer system may be treating this as a single order with two bottles, A (D5/0.45NaCl 1000mL @ 100mL/hr) and B (D5/0.45NaCl + 20mEq KCL 1000mL @ 100mL/hr), repeating in the cycle of A-A-B with a cyclical component (multi-vitamins).

The parent:

ORC|NW|134^SMS|||||1^C^^200611280900^^R^^^^C|...<cr>

RXO|Cyclic IV|...<cr>

The first child:

ORC|CH|134A1^SMS|||||1^C^^^^^^^^C&134B&SMS&&&*ES+0M|134|...<cr>

RXO Segment, Requested Give Amount-Minimum: ...|100||ML|...

Requested Give Per (Time Unit): ...|H1|...<cr>

RXR|IV|...<cr>

RXC|B|D5/.45NACL|1000|ML|...<cr>

The second child:

ORC|CH|134A2^SMS|||||1^C^^^^^^^^C&134A1&SMS&&&ES+0M|134|...<cr>

RXO Segment, Requested Give Amount-Minimum: ...|100||ML|...

Requested Give Per (Time Unit): ...|H1|...<cr>

RXR|IV|...<cr>

RXC|B|D5/.45NACL|1000|ML|...<cr>

The third child:

ORC|CH|134B^SMS|||||1^C^^^^^^^^C&134A2&SMS&&&#ES+0M|134|...<cr>

RXO Segment, Requested Give Amount-Minimum: ...|100||ML|...

Requested Give Per (Time Unit): ...|H1|...<cr>

RXR|IV|...<cr>

RXC|B|D5/.45NACL|1000|ML|...<cr>

RXC|A|KCL|20|MEQ|...<cr>

The fourth child:

ORC|CH|134X^SMS|||||1^Q1D^^^^^^^^|134|...<cr>

RXO|MULTIVITAMINS|10||ML|INJECTABLE|...<cr>

Discussion points:

This method for accommodating the Multi-vitamins Daily scenario does not pretend to be the best or only way to express the message, but simply demonstrates adapting the current specification to a highly complex order without adding new components.

The Multi-vitamins component may be sent as a fourth child.

In this example, its _ORC-7-quantity/timing_ includes an interval of "Q1D" (every 1 days).

Its order number consists of the placer's parent order number plus an appended identifier ('X' in the above example) that labels this child as a special case. This convention would need to be agreed upon by sending and receiving applications.

{empty}d) Example #4

D5W + 40mEq KCl 1000mL alternating with D5/LR + 20mEq KCl 1000mL alternating with D5/0.45NaCl 1000mL. Infuse the D5W and D5/0.45 at 125mL/hr, and the D5/LR at 100mL/hr.

(Other message data: placer order #177, placer application ID=SMS, interval=continuous, start date/time=11/28/94 0900, no stop date/time, priority=Routine, order sequencing=Cyclical)

This example is another variation of Example 1 where the rate for each bottle is different, and this can be expressed within the RX segments of the children using current components. In this example, the placer system deals with this as one order with three alternating bottles, A (D5W + 40mEq KCl 1000mL @ 125mL/hr) , B (D5/LR + 20mEq KCl 1000mL @ 100mL/hr) , and C (D5/0.45NaCl 1000mL @ 125mL/hr) in the cycle A-B-C. The principles discussed in Example #1 apply equally to this example.

The parent:

ORC|NW|177^SMS|||||1^C^^200611280900^^R^^^^C|...<cr>

RXO|Cyclic IV|...<cr>

The first child:

ORC|CH|177A^SMS|||||1^C^^^^^^^^C&177C&SMS&&&*ES+0M|177|...<cr>

RXO Segment, Requested Give Amount-Minimum: ...|125||ML|...

Requested Give Per (Time Unit): ...|H1|...<cr>

RXR|IV|...<cr>

RXC|B|D5W|1000|ML|...<cr>

RXC|A|KCL|40|MEQ|...<cr>

The second child:

ORC|CH|177B^SMS|||||1^C^^^^^^^^C&177A&SMS&&&ES+0M|177|...<cr>

RXO Segment, Requested Give Amount-Minimum: ...|100||ML|...

Requested Give Per (Time Unit): ...|H1|...<cr>

RXR|IV|...<cr>

RXC|B|D5/LR|1000|ML|...<cr>

RXC|A|KCL|20|MEQ|...<cr>

The third child:

ORC|CH|177C^SMS|||||1^C^^^^^^^^C&177B&SMS&&&#ES+0M|177|...<cr>

RXO Segment, Requested Give Amount-Minimum: ...|125||ML|...

Requested Give Per (Time Unit): ...|H1|...<cr>

RXR|IV|...<cr>

RXC|B|D5/0.45NACL|1000|ML|...<cr>

=== Query examples

